### ISSUE TITLE
xmipp movie extract particle fails

### ISSUE THREAD

**Issue by yaizar** [I2PC/scipion#1024]
```
00001:   RUNNING PROTOCOL -----------------
00002:             PID: 14990
00003:         Scipion: v1.1-beta (2017-04-21) Balbino
00004:      currentDir: /home/yaiza/ScipionUserData/projects/TestExtractMovieParticles
00005:      workingDir: Runs/002126_XmippProtExtractMovieParticles
00006:         runMode: Continue
00007:             MPI: 1
00008:         threads: 3
00009:   len(steps) 2 len(prevSteps) 0 
00010:    Starting at step: 1
00011:    Running steps 
00012:   STARTED: processMovieStep, step 1
00013:     2017-05-24 11:17:44.796136
00014:   Processing movie: Runs/002126_XmippProtExtractMovieParticles/tmp/movie_000001/Falcon_2012_06_12-16_55_40_0_movie.mrcs
00015:   Index:  0 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
00016:   Writing coordinates metadata: Runs/002126_XmippProtExtractMovieParticles/tmp/movie_000001/frame_01_coordinates.xmd, with shifts: 0 0
00017:   Writing frame: Runs/002126_XmippProtExtractMovieParticles/tmp/movie_000001/frame_01.mrc
00018:   Passing Ih:  1 Runs/002126_XmippProtExtractMovieParticles/tmp/movie_000001/Falcon_2012_06_12-16_55_40_0_movie.mrcs Runs/002126_XmippProtExtractMovieParticles/tmp/movie_000001/frame_01.mrc
00019:   Removing Dust
00020:   xmipp_transform_filter  -i Runs/002126_XmippProtExtractMovieParticles/tmp/movie_000001/frame_01.mrc -o Runs/002126_XmippProtExtractMovieParticles/tmp/movie_000001/frame_01.mrc --bad_pixels outliers 3.500000
00021:   Input File: Runs/002126_XmippProtExtractMovieParticles/tmp/movie_000001/frame_01.mrc
00022:   Output File: Runs/002126_XmippProtExtractMovieParticles/tmp/movie_000001/frame_01.mrc
00023:      1/   1 sec. ............................................................
00024:   Extracting particles
00025:   xmipp_micrograph_scissor -i Runs/002126_XmippProtExtractMovieParticles/tmp/movie_000001/frame_01.mrc --pos Runs/002126_XmippProtExtractMovieParticles/tmp/movie_000001/frame_01_coordinates.xmd -o Runs/002126_XmippProtExtractMovieParticles/tmp/movie_000001/frame_01_images --Xdim 80 --downsampling 1.000000 
00026:   XMIPP_ERROR 47:  Incorrect MultidimArray dimensions.
00027:   Micrograph::open_micrograph: Only files with a single micrograph may be processed. Error reading Runs/002126_XmippProtExtractMovieParticles/tmp/movie_000001/frame_01.mrc
00028:   File: software/em/xmipp/libraries/data/micrograph.cpp line: 95
00029:   Traceback (most recent call last):
00030:     File "/home/yaiza/scipion/scipion/pyworkflow/protocol/executor.py", line 137, in run
00031:       self.step._run()  # not self.step.run() , to avoid race conditions
00032:     File "/home/yaiza/scipion/scipion/pyworkflow/protocol/protocol.py", line 228, in _run
00033:       resultFiles = self._runFunc()
00034:     File "/home/yaiza/scipion/scipion/pyworkflow/protocol/protocol.py", line 224, in _runFunc
00035:       return self._func(*self._args)
00036:     File "/home/yaiza/scipion/scipion/pyworkflow/em/protocol/protocol_movies.py", line 267, in processMovieStep
00037:       self._processMovie(movie)
00038:     File "/home/yaiza/scipion/scipion/pyworkflow/em/packages/xmipp3/protocol_extract_particles_movies.py", line 245, in _processMovie
00039:       self.runJob('xmipp_micrograph_scissor', args)
00040:     File "/home/yaiza/scipion/scipion/pyworkflow/protocol/protocol.py", line 1077, in runJob
00041:       self._stepsExecutor.runJob(self._log, program, arguments, **kwargs)
00042:     File "/home/yaiza/scipion/scipion/pyworkflow/protocol/executor.py", line 56, in runJob
00043:       env=env, cwd=cwd)
00044:     File "/home/yaiza/scipion/scipion/pyworkflow/utils/process.py", line 51, in runJob
00045:       return runCommand(command, env, cwd)
00046:     File "/home/yaiza/scipion/scipion/pyworkflow/utils/process.py", line 65, in runCommand
00047:       check_call(command, shell=True, stdout=sys.stdout, stderr=sys.stderr, env=env, cwd=cwd)
00048:     File "/home/yaiza/scipion/scipion/software/lib/python2.7/subprocess.py", line 540, in check_call
00049:       raise CalledProcessError(retcode, cmd)
00050:   CalledProcessError: Command 'xmipp_micrograph_scissor -i Runs/002126_XmippProtExtractMovieParticles/tmp/movie_000001/frame_01.mrc --pos Runs/002126_XmippProtExtractMovieParticles/tmp/movie_000001/frame_01_coordinates.xmd -o Runs/002126_XmippProtExtractMovieParticles/tmp/movie_000001/frame_01_images --Xdim 80 --downsampling 1.000000 ' returned non-zero exit status 47
00051:   Protocol failed: Command 'xmipp_micrograph_scissor -i Runs/002126_XmippProtExtractMovieParticles/tmp/movie_000001/frame_01.mrc --pos Runs/002126_XmippProtExtractMovieParticles/tmp/movie_000001/frame_01_coordinates.xmd -o Runs/002126_XmippProtExtractMovieParticles/tmp/movie_000001/frame_01_images --Xdim 80 --downsampling 1.000000 ' returned non-zero exit status 47
00052:   FAILED: processMovieStep, step 1
00053:     2017-05-24 11:17:56.117346
00054:   Not cleaning temporarly files since SCIPION_DEBUG_NOCLEAN is set to True.
00055:   ------------------- PROTOCOL FAILED (DONE 1/2)
```

**Comment by yaizar** [comment]
In a different project:

```
00001:   RUNNING PROTOCOL -----------------
00002:             PID: 26304
00003:         Scipion: v1.1-beta (2017-04-21) Balbino
00004:      currentDir: /home/yaiza/ScipionUserData/projects/workflow_laura
00005:      workingDir: Runs/002192_XmippProtExtractMovieParticles
00006:         runMode: Restart
00007:             MPI: 1
00008:         threads: 3
00009:    Starting at step: 1
00010:    Running steps 
00011:   STARTED: processMovieStep, step 1
00012:     2017-05-22 15:21:14.765756
00013:   STARTED: processMovieStep, step 2
00014:     2017-05-22 15:21:14.768037
00015:   Micrograph with id 2 was not found in SetOfCoordinates!!!
00016:   Processing movie: Runs/002192_XmippProtExtractMovieParticles/tmp/movie_000001/Falcon_2012_06_12-14_33_35_0_movie.mrcs
00017:   Index:  0 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
00018:   Writing coordinates metadata: Runs/002192_XmippProtExtractMovieParticles/tmp/movie_000001/frame_01_coordinates.xmd, with shifts: 0 0
00019:   Writing frame: Runs/002192_XmippProtExtractMovieParticles/tmp/movie_000001/frame_01.mrc
00020:   Passing Ih:  1 Runs/002192_XmippProtExtractMovieParticles/tmp/movie_000001/Falcon_2012_06_12-14_33_35_0_movie.mrcs Runs/002192_XmippProtExtractMovieParticles/tmp/movie_000001/frame_01.mrc
00021:   Removing Dust
00022:   xmipp_transform_filter  -i Runs/002192_XmippProtExtractMovieParticles/tmp/movie_000001/frame_01.mrc -o Runs/002192_XmippProtExtractMovieParticles/tmp/movie_000001/frame_01.mrc --bad_pixels outliers 3.500000
00023:   FINISHED: processMovieStep, step 2
00024:     2017-05-22 15:21:14.773723
00025:   STARTED: processMovieStep, step 3
00026:     2017-05-22 15:21:15.279897
00027:   Micrograph with id 3 was not found in SetOfCoordinates!!!
00028:   Input File: Runs/002192_XmippProtExtractMovieParticles/tmp/movie_000001/frame_01.mrc
00029:   Output File: Runs/002192_XmippProtExtractMovieParticles/tmp/movie_000001/frame_01.mrc
00030:      0/   0 sec. .....................................FINISHED: processMovieStep, step 3
00031:     2017-05-22 15:21:15.282317
00032:   STARTED: processMovieStep, step 4
00033:     2017-05-22 15:21:15.788504
00034:   Processing movie: Runs/002192_XmippProtExtractMovieParticles/tmp/movie_000004/Falcon_2012_06_12-15_41_22_0_movie.mrcs
00035:      0/   0 sec. .............................................Index:  0 [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]
00036:   Writing coordinates metadata: Runs/002192_XmippProtExtractMovieParticles/tmp/movie_000004/frame_01_coordinates.xmd, with shifts: 0 0
00037:      0/   0 sec. ................................................Writing frame: Runs/002192_XmippProtExtractMovieParticles/tmp/movie_000004/frame_01.mrc
00038:      1/   1 sec. ............................................................
00039:   Passing Ih:  1 Runs/002192_XmippProtExtractMovieParticles/tmp/movie_000004/Falcon_2012_06_12-15_41_22_0_movie.mrcs Runs/002192_XmippProtExtractMovieParticles/tmp/movie_000004/frame_01.mrc
00040:   Removing Dust
00041:   Extracting particles
00042:   xmipp_transform_filter  -i Runs/002192_XmippProtExtractMovieParticles/tmp/movie_000004/frame_01.mrc -o Runs/002192_XmippProtExtractMovieParticles/tmp/movie_000004/frame_01.mrc --bad_pixels outliers 3.500000
00043:   xmipp_micrograph_scissor -i Runs/002192_XmippProtExtractMovieParticles/tmp/movie_000001/frame_01.mrc --pos Runs/002192_XmippProtExtractMovieParticles/tmp/movie_000001/frame_01_coordinates.xmd -o Runs/002192_XmippProtExtractMovieParticles/tmp/movie_000001/frame_01_images --Xdim 88 --downsampling 1.000000 
00044:   XMIPP_ERROR 47:  Incorrect MultidimArray dimensions.
00045:   Micrograph::open_micrograph: Only files with a single micrograph may be processed. Error reading Runs/002192_XmippProtExtractMovieParticles/tmp/movie_000001/frame_01.mrc
00046:   File: software/em/xmipp/libraries/data/micrograph.cpp line: 95
00047:   Input File: Runs/002192_XmippProtExtractMovieParticles/tmp/movie_000004/frame_01.mrc
00048:   Output File: Runs/002192_XmippProtExtractMovieParticles/tmp/movie_000004/frame_01.mrc
00049:      0/   0 sec. ..............................Traceback (most recent call last):
00050:     File "/home/yaiza/scipion/pyworkflow/protocol/executor.py", line 137, in run
00051:       self.step._run()  # not self.step.run() , to avoid race conditions
00052:     File "/home/yaiza/scipion/pyworkflow/protocol/protocol.py", line 228, in _run
00053:       resultFiles = self._runFunc()
00054:     File "/home/yaiza/scipion/pyworkflow/protocol/protocol.py", line 224, in _runFunc
00055:       return self._func(*self._args)
00056:     File "/home/yaiza/scipion/pyworkflow/em/protocol/protocol_movies.py", line 267, in processMovieStep
00057:       self._processMovie(movie)
00058:     File "/home/yaiza/scipion/pyworkflow/em/packages/xmipp3/protocol_extract_particles_movies.py", line 243, in _processMovie
00059:       self.runJob('xmipp_micrograph_scissor', args)
00060:     File "/home/yaiza/scipion/pyworkflow/protocol/protocol.py", line 1077, in runJob
00061:       self._stepsExecutor.runJob(self._log, program, arguments, **kwargs)
00062:     File "/home/yaiza/scipion/pyworkflow/protocol/executor.py", line 56, in runJob
00063:       env=env, cwd=cwd)
00064:     File "/home/yaiza/scipion/pyworkflow/utils/process.py", line 51, in runJob
00065:       return runCommand(command, env, cwd)
00066:     File "/home/yaiza/scipion/pyworkflow/utils/process.py", line 65, in runCommand
00067:       check_call(command, shell=True, stdout=sys.stdout, stderr=sys.stderr, env=env, cwd=cwd)
00068:     File "/home/yaiza/scipion/software/lib/python2.7/subprocess.py", line 540, in check_call
00069:       raise CalledProcessError(retcode, cmd)
00070:   CalledProcessError: Command 'xmipp_micrograph_scissor -i Runs/002192_XmippProtExtractMovieParticles/tmp/movie_000001/frame_01.mrc --pos Runs/002192_XmippProtExtractMovieParticles/tmp/movie_000001/frame_01_coordinates.xmd -o Runs/002192_XmippProtExtractMovieParticles/tmp/movie_000001/frame_01_images --Xdim 88 --downsampling 1.000000 ' returned non-zero exit status 47
00071:   Protocol failed: Command 'xmipp_micrograph_scissor -i Runs/002192_XmippProtExtractMovieParticles/tmp/movie_000001/frame_01.mrc --pos Runs/002192_XmippProtExtractMovieParticles/tmp/movie_000001/frame_01_coordinates.xmd -o Runs/002192_XmippProtExtractMovieParticles/tmp/movie_000001/frame_01_images --Xdim 88 --downsampling 1.000000 ' returned non-zero exit status 47
00072:   FAILED: processMovieStep, step 1
00073:     2017-05-22 15:21:16.351145
00074:      0/   0 sec. .................................Not cleaning temporarly files since SCIPION_DEBUG_NOCLEAN is set to True.
00075:   ------------------- PROTOCOL FAILED (DONE 3/16)
00076:      1/   1 sec. ............................................................
```

**Comment by yaizar** [comment]
So it looks like a problem with movies in .mrcs format. [This line](https://github.com/I2PC/scipion/blob/release-1.1/pyworkflow/em/packages/xmipp3/protocol_extract_particles_movies.py#L229) is supposed to create a mrc file with a frame, but it just copies the whole movie to a new mrc file. For movies with other formats it works fine. If we call `xmipp_micrograph_scissor` with `<frame_num>@<movie_name.mrcs>` instead of writing the frame, it works.
