### ISSUE TITLE
Xmipp CTF wizard not working

### ISSUE THREAD

**Issue by cossorzano** [I2PC/scipion#1076]
It gives the error

Exception in Tkinter callback
Traceback (most recent call last):
  File "/media/coss/f3cf45f0-2cc3-4161-94e7-5f1c70af2e45/scipion/scipion/software/lib/python2.7/lib-tk/Tkinter.py", line 1486, in __call__
    return self.func(*args)
  File "/media/coss/f3cf45f0-2cc3-4161-94e7-5f1c70af2e45/scipion/scipion/pyworkflow/gui/form.py", line 788, in _showWizard
    wizard.show(self.window)
  File "/media/coss/f3cf45f0-2cc3-4161-94e7-5f1c70af2e45/scipion/scipion/pyworkflow/em/packages/xmipp3/wizard.py", line 116, in show
    d = CtfDownsampleDialog(form.root, provider, **args)
  File "/media/coss/f3cf45f0-2cc3-4161-94e7-5f1c70af2e45/scipion/scipion/pyworkflow/em/wizard.py", line 416, in __init__
    buttons=buttons, default='Select', **args)
  File "/media/coss/f3cf45f0-2cc3-4161-94e7-5f1c70af2e45/scipion/scipion/pyworkflow/gui/dialog.py", line 87, in __init__
    self.body(bodyFrame)
  File "/media/coss/f3cf45f0-2cc3-4161-94e7-5f1c70af2e45/scipion/scipion/pyworkflow/em/wizard.py", line 436, in body
    self._createPreview(previewFrame)
  File "/media/coss/f3cf45f0-2cc3-4161-94e7-5f1c70af2e45/scipion/scipion/pyworkflow/em/wizard.py", line 524, in _createPreview
    self.rightPreview = self._createRightPreview(rightFrame)
  File "/media/coss/f3cf45f0-2cc3-4161-94e7-5f1c70af2e45/scipion/scipion/pyworkflow/em/wizard.py", line 574, in _createRightPreview
    label=self.rightPreviewLabel)
  File "/media/coss/f3cf45f0-2cc3-4161-94e7-5f1c70af2e45/scipion/scipion/pyworkflow/gui/matplotlib_image.py", line 127, in __init__
    Preview.__init__(self, master, dim, dpi, label)
  File "/media/coss/f3cf45f0-2cc3-4161-94e7-5f1c70af2e45/scipion/scipion/pyworkflow/gui/matplotlib_image.py", line 79, in __init__
    self.bg = np.zeros((dim, dim), float)
TypeError: 'float' object cannot be interpreted as an index

**Comment by pconesa** [comment]
@cossorzano , can we close this?
