### ISSUE TITLE
Manager used in scripts with no GUI... fails

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion#1108]
In machines with no GUI using the scripts (in this case the create_project.py)....we are getting errors:

Scipion  release-1.1-headless-devel (2017-07-07) f9ee9af

 

>>>>> python  "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/scripts/create_project.py" "name1" "/dls/m02/data/2017/cm16766-3/processed/scipion_template_20170707_1034.json" "/dls/m02/data/2017/cm16766-3/processed/"

creating a project at /dls/m02/data/2017/cm16766-3/processed/name1

(the default location would have been /localhome/gda2/ScipionUserData/projects/name1

Creating project at:  /dls/m02/data/2017/cm16766-3/processed/name1/project.sqlite

>>> Error loading module: 'motioncorr'

>>> Exception:  libXss.so.1: cannot open shared object file: No such file or directory

Traceback (most recent call last):

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/pyworkflow/utils/reflection.py", line 49, in getModules

    m = __import__(f)

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/pyworkflow/em/packages/motioncorr/__init__.py", line 31, in <module>

    from protocol_motioncorr import ProtMotionCorr

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/pyworkflow/em/packages/motioncorr/protocol_motioncorr.py", line 39, in <module>

    from pyworkflow.em.packages.xmipp3.convert import writeShiftsMovieAlignment

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/pyworkflow/em/packages/xmipp3/__init__.py", line 54, in <module>

    from viewer_resolution_monogenic_signal import XmippMonoResViewer

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/pyworkflow/em/packages/xmipp3/viewer_resolution_monogenic_signal.py", line 35, in <module>

    import matplotlib.pyplot as plt

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/software/lib/python2.7/site-packages/matplotlib-1.3.1-py2.7-linux-x86_64.egg/matplotlib/pyplot.py", line 98, in <module>

    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/software/lib/python2.7/site-packages/matplotlib-1.3.1-py2.7-linux-x86_64.egg/matplotlib/backends/__init__.py", line 28, in pylab_setup

    globals(),locals(),[backend_name],0)

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/software/lib/python2.7/site-packages/matplotlib-1.3.1-py2.7-linux-x86_64.egg/matplotlib/backends/backend_tkagg.py", line 11, in <module>

    import matplotlib.backends.tkagg as tkagg

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/software/lib/python2.7/site-packages/matplotlib-1.3.1-py2.7-linux-x86_64.egg/matplotlib/backends/tkagg.py", line 2, in <module>

    from matplotlib.backends import _tkagg

ImportError: libXss.so.1: cannot open shared object file: No such file or directory

>>> Error loading module: 'bsoft'

>>> Exception:  libXss.so.1: cannot open shared object file: No such file or directory

Traceback (most recent call last):

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/pyworkflow/utils/reflection.py", line 49, in getModules

    m = __import__(f)

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/pyworkflow/em/packages/bsoft/__init__.py", line 36, in <module>

    from protocol_particle_pick import BsoftProtParticlePicking

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/pyworkflow/em/packages/bsoft/protocol_particle_pick.py", line 30, in <module>

   from convert import readSetOfCoordinates

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/pyworkflow/em/packages/bsoft/convert.py", line 10, in <module>

    from pyworkflow.em.packages.xmipp3.convert import rowToCoordinate, rowFromMd

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/pyworkflow/em/packages/xmipp3/__init__.py", line 54, in <module>

    from viewer_resolution_monogenic_signal import XmippMonoResViewer

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/pyworkflow/em/packages/xmipp3/viewer_resolution_monogenic_signal.py", line 35, in <module>

    import matplotlib.pyplot as plt

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/software/lib/python2.7/site-packages/matplotlib-1.3.1-py2.7-linux-x86_64.egg/matplotlib/pyplot.py", line 98, in <module>

    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/software/lib/python2.7/site-packages/matplotlib-1.3.1-py2.7-linux-x86_64.egg/matplotlib/backends/__init__.py", line 28, in pylab_setup

    globals(),locals(),[backend_name],0)

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/software/lib/python2.7/site-packages/matplotlib-1.3.1-py2.7-linux-x86_64.egg/matplotlib/backends/backend_tkagg.py", line 11, in <module>

    import matplotlib.backends.tkagg as tkagg

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/software/lib/python2.7/site-packages/matplotlib-1.3.1-py2.7-linux-x86_64.egg/matplotlib/backends/tkagg.py", line 2, in <module>

    from matplotlib.backends import _tkagg

ImportError: libXss.so.1: cannot open shared object file: No such file or directory

>>> Error loading module: 'relion'

>>> Exception:  libXss.so.1: cannot open shared object file: No such file or directory

Traceback (most recent call last):

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/pyworkflow/utils/reflection.py", line 49, in getModules

    m = __import__(f)

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/pyworkflow/em/packages/relion/__init__.py", line 34, in <module>

    from convert import *

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/pyworkflow/em/packages/relion/convert.py", line 41, in <module>

    from pyworkflow.em.packages.relion.constants import V1_3, V1_4, V2_0

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/pyworkflow/em/packages/relion/__init__.py", line 53, in <module>

    from wizard import *

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/pyworkflow/em/packages/relion/wizard.py", line 27, in <module>

    from pyworkflow.em.packages.xmipp3.constants import *

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/pyworkflow/em/packages/xmipp3/__init__.py", line 54, in <module>

    from viewer_resolution_monogenic_signal import XmippMonoResViewer

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/pyworkflow/em/packages/xmipp3/viewer_resolution_monogenic_signal.py", line 35, in <module>

    import matplotlib.pyplot as plt

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/software/lib/python2.7/site-packages/matplotlib-1.3.1-py2.7-linux-x86_64.egg/matplotlib/pyplot.py", line 98, in <module>

    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/software/lib/python2.7/site-packages/matplotlib-1.3.1-py2.7-linux-x86_64.egg/matplotlib/backends/__init__.py", line 28, in pylab_setup

    globals(),locals(),[backend_name],0)

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/software/lib/python2.7/site-packages/matplotlib-1.3.1-py2.7-linux-x86_64.egg/matplotlib/backends/backend_tkagg.py", line 11, in <module>

    import matplotlib.backends.tkagg as tkagg

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/software/lib/python2.7/site-packages/matplotlib-1.3.1-py2.7-linux-x86_64.egg/matplotlib/backends/tkagg.py", line 2, in <module>

    from matplotlib.backends import _tkagg

ImportError: libXss.so.1: cannot open shared object file: No such file or directory

>>> Error loading module: 'eman2'

>>> Exception:  libXss.so.1: cannot open shared object file: No such file or directory

Traceback (most recent call last):

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/pyworkflow/utils/reflection.py", line 49, in getModules

    m = __import__(f)

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/pyworkflow/em/packages/eman2/__init__.py", line 37, in <module>

    from protocol_boxing import EmanProtBoxing

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/pyworkflow/em/packages/eman2/protocol_boxing.py", line 36, in <module>

    from pyworkflow.em.packages.eman2.convert import loadJson

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/pyworkflow/em/packages/eman2/__init__.py", line 42, in <module>

    from viewer import EmanViewer, RefineEasyViewer

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/pyworkflow/em/packages/eman2/viewer.py", line 35, in <module>

    from pyworkflow.em.packages.xmipp3.viewer import XmippViewer

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/pyworkflow/em/packages/xmipp3/__init__.py", line 54, in <module>

    from viewer_resolution_monogenic_signal import XmippMonoResViewer

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/pyworkflow/em/packages/xmipp3/viewer_resolution_monogenic_signal.py", line 35, in <module>

    import matplotlib.pyplot as plt

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/software/lib/python2.7/site-packages/matplotlib-1.3.1-py2.7-linux-x86_64.egg/matplotlib/pyplot.py", line 98, in <module>

    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/software/lib/python2.7/site-packages/matplotlib-1.3.1-py2.7-linux-x86_64.egg/matplotlib/backends/__init__.py", line 28, in pylab_setup

    globals(),locals(),[backend_name],0)

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/software/lib/python2.7/site-packages/matplotlib-1.3.1-py2.7-linux-x86_64.egg/matplotlib/backends/backend_tkagg.py", line 11, in <module>

    import matplotlib.backends.tkagg as tkagg

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/software/lib/python2.7/site-packages/matplotlib-1.3.1-py2.7-linux-x86_64.egg/matplotlib/backends/tkagg.py", line 2, in <module>

    from matplotlib.backends import _tkagg

ImportError: libXss.so.1: cannot open shared object file: No such file or directory

>>> Error loading module: 'spider'

>>> Exception:  libXss.so.1: cannot open shared object file: No such file or directory

Traceback (most recent call last):

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/pyworkflow/utils/reflection.py", line 49, in getModules

    m = __import__(f)

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/pyworkflow/em/packages/spider/__init__.py", line 42, in <module>

    from viewer import SpiderViewer

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/pyworkflow/em/packages/spider/viewer.py", line 32, in <module>

    from pyworkflow.em.packages.xmipp3.viewer import XmippViewer

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/pyworkflow/em/packages/xmipp3/__init__.py", line 54, in <module>

    from viewer_resolution_monogenic_signal import XmippMonoResViewer

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/pyworkflow/em/packages/xmipp3/viewer_resolution_monogenic_signal.py", line 35, in <module>

    import matplotlib.pyplot as plt

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/software/lib/python2.7/site-packages/matplotlib-1.3.1-py2.7-linux-x86_64.egg/matplotlib/pyplot.py", line 98, in <module>

    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/software/lib/python2.7/site-packages/matplotlib-1.3.1-py2.7-linux-x86_64.egg/matplotlib/backends/__init__.py", line 28, in pylab_setup

    globals(),locals(),[backend_name],0)

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/software/lib/python2.7/site-packages/matplotlib-1.3.1-py2.7-linux-x86_64.egg/matplotlib/backends/backend_tkagg.py", line 11, in <module>

    import matplotlib.backends.tkagg as tkagg

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/software/lib/python2.7/site-packages/matplotlib-1.3.1-py2.7-linux-x86_64.egg/matplotlib/backends/tkagg.py", line 2, in <module>

    from matplotlib.backends import _tkagg

ImportError: libXss.so.1: cannot open shared object file: No such file or directory

>>> Error loading module: 'xmipp3'

>>> Exception:  libXss.so.1: cannot open shared object file: No such file or directory

Traceback (most recent call last):

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/pyworkflow/utils/reflection.py", line 49, in getModules

    m = __import__(f)

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/pyworkflow/em/packages/xmipp3/__init__.py", line 36, in <module>

    from convert import *

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/pyworkflow/em/packages/xmipp3/convert.py", line 40, in <module>

    from pyworkflow.em.packages.xmipp3.utils import iterMdRows

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/pyworkflow/em/packages/xmipp3/__init__.py", line 54, in <module>

    from viewer_resolution_monogenic_signal import XmippMonoResViewer

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/pyworkflow/em/packages/xmipp3/viewer_resolution_monogenic_signal.py", line 35, in <module>

    import matplotlib.pyplot as plt

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/software/lib/python2.7/site-packages/matplotlib-1.3.1-py2.7-linux-x86_64.egg/matplotlib/pyplot.py", line 98, in <module>

    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/software/lib/python2.7/site-packages/matplotlib-1.3.1-py2.7-linux-x86_64.egg/matplotlib/backends/__init__.py", line 28, in pylab_setup

    globals(),locals(),[backend_name],0)

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/software/lib/python2.7/site-packages/matplotlib-1.3.1-py2.7-linux-x86_64.egg/matplotlib/backends/backend_tkagg.py", line 11, in <module>

    import matplotlib.backends.tkagg as tkagg

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/software/lib/python2.7/site-packages/matplotlib-1.3.1-py2.7-linux-x86_64.egg/matplotlib/backends/tkagg.py", line 2, in <module>

    from matplotlib.backends import _tkagg

ImportError: libXss.so.1: cannot open shared object file: No such file or directory

>>> Error loading module: 'gautomatch'

>>> Exception:  libXss.so.1: cannot open shared object file: No such file or directory

Traceback (most recent call last):

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/pyworkflow/utils/reflection.py", line 49, in getModules

    m = __import__(f)

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/pyworkflow/em/packages/gautomatch/__init__.py", line 36, in <module>

    from viewer import GautomatchViewer

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/pyworkflow/em/packages/gautomatch/viewer.py", line 33, in <module>

    from pyworkflow.em.packages.xmipp3.convert import *

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/pyworkflow/em/packages/xmipp3/__init__.py", line 54, in <module>

    from viewer_resolution_monogenic_signal import XmippMonoResViewer

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/pyworkflow/em/packages/xmipp3/viewer_resolution_monogenic_signal.py", line 35, in <module>

    import matplotlib.pyplot as plt

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/software/lib/python2.7/site-packages/matplotlib-1.3.1-py2.7-linux-x86_64.egg/matplotlib/pyplot.py", line 98, in <module>

    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/software/lib/python2.7/site-packages/matplotlib-1.3.1-py2.7-linux-x86_64.egg/matplotlib/backends/__init__.py", line 28, in pylab_setup

    globals(),locals(),[backend_name],0)

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/software/lib/python2.7/site-packages/matplotlib-1.3.1-py2.7-linux-x86_64.egg/matplotlib/backends/backend_tkagg.py", line 11, in <module>

    import matplotlib.backends.tkagg as tkagg

  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/software/lib/python2.7/site-packages/matplotlib-1.3.1-py2.7-linux-x86_64.egg/matplotlib/backends/tkagg.py", line 2, in <module>

    from matplotlib.backends import _tkagg

ImportError: libXss.so.1: cannot open shared object file: No such file or directory

ERROR: protocol class name 'ProtMotionCorr' not found

**Comment by delarosatrevin** [comment]
The problem is here:
```
from viewer_resolution_monogenic_signal import XmippMonoResViewer
File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/pyworkflow/em/packages/xmipp3/viewer_resolution_monogenic_signal.py", line 35, in

import matplotlib.pyplot as plt
```
the "plt" should be imported from our own plotter module, like:

```
from pyworkflow.gui.plotter import plt
```

In there we added the following protection to work properly when there is no GUI:

```
try:
    import matplotlib.pyplot as plt
except:
    plt = None
```

The problem is that this can easily be forgotten by developers of new viewers like in this case. I don't see a more general way right now to force that.

**Comment by pconesa** [comment]
Thanks Jose

**Comment by delarosatrevin** [comment]
@pconesa Has this been addressed? Can this issue be closed?

**Comment by pconesa** [comment]
Don't think so, how is to simulate a "non GUI" environment?

**Comment by delarosatrevin** [comment]
I'm not sure about how to simulate it...make rename some basic X11 libraries...but not sure how safe is this.  But when I was on Diamond we manage to bypass all matplotlib includes...I'm not sure if this viewer still includes directly the matplotlib or the one in our modules (the way to be more robust to no gui environments)

**Comment by delarosatrevin** [comment]
@pconesa Has this been fixed?
