### ISSUE TITLE
Scipion read-only

### ISSUE THREAD

**Issue by ldelcano** [I2PC/scipion#1112]
Investigate what changes are needed to support Scipion read-only.

**Comment by kevinpetersavage** [comment]
I've been looking into this as @pconesa contributed a fix to te release-1.1-headless-devel branch we are using. I see this when I try and open a read only imported project: 

/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/software/lib/python2.7/site-packages/setuptools-5.4.1-py2.7.egg/pkg_resources.py:1049: UserWarning: /home/nnp95151/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
PROJECT: Warning, protocol view 'None' not found.
         Using 'Protocols SPA' instead.
Error trying to update protocol: (jobId=21687)
 ERROR: attempt to write a readonly database, tries=0
Error trying to update protocol: (jobId=21823)
 ERROR: attempt to write a readonly database, tries=1
Error trying to update protocol: (jobId=21823)
 ERROR: attempt to write a readonly database, tries=2
Error trying to update protocol: (jobId=21823)
 ERROR: attempt to write a readonly database, tries=3
Traceback (most recent call last):
  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/pyworkflow/project.py", line 490, in _updateProtocol
    protocol.copy(prot2, copyId=False)
  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/pyworkflow/protocol/protocol.py", line 1015, in copy
    self._store()
  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/pyworkflow/protocol/protocol.py", line 676, in _store
    self.mapper.store(self)
  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/pyworkflow/mapper/mapper.py", line 129, in store
    self.updateTo(obj)
  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/pyworkflow/mapper/sqlite.py", line 139, in updateTo
    self.__updateTo(obj, level)
  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/pyworkflow/mapper/sqlite.py", line 155, in __updateTo
    obj._objLabel, obj._objComment)
  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/pyworkflow/mapper/sqlite.py", line 597, in updateObject
    (parent_id, name, classname, value, label, comment, objId))
OperationalError: attempt to write a readonly database
attempt to write a readonly database

**Comment by pconesa** [comment]
Hi @kevinpetersavage , this is not expect to happen unless you are dealing with old code. Could you confirm this is with new code that has the readonly changes? I'm confused.
