### ISSUE TITLE
Showj crashes when visualizing CTFs and trying to recalculate

### ISSUE THREAD

**Issue by delarosatrevin** [I2PC/scipion#1181]
I don't have a very well defined path to reproduce this error, but it happens quite often when visualizing the result of a SetOfMicrographs and trying to recalculate the CTF for some of them. I have got the following exception in the console:

Exception in thread "Run$_AWT-EventQueue-0" java.lang.NullPointerException
        at ij.plugin.frame.Recorder.record(Recorder.java:221)
        at ij.gui.EllipseRoi.handleMouseUp(EllipseRoi.java:107)
        at ij.gui.ImageCanvas.mouseReleased(ImageCanvas.java:1440)
        at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:289)
        at java.awt.Component.processMouseEvent(Component.java:6533)
        at java.awt.Component.processEvent(Component.java:6298)
        at java.awt.Component.dispatchEventImpl(Component.java:4889)
        at java.awt.Component.dispatchEvent(Component.java:4711)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
        at java.awt.EventQueue$4.run(EventQueue.java:731)
        at java.awt.EventQueue$4.run(EventQueue.java:729)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

**Comment by pconesa** [comment]
Thanks Jose...couldn't reproduce it here but will investigate. Good to know this is happening.
