### ISSUE TITLE
Bug when trying to open a path from OutputLog

### ISSUE THREAD

**Issue by delarosatrevin** [I2PC/scipion#1183]
In the OutputLog of any protocol, one can select a path, then right click and 'Open path', this is not working now. The following exception is thrown:

Exception in Tkinter callback
Traceback (most recent call last):
  File "/data/josem/work/devel/scipion/software/lib/python2.7/lib-tk/Tkinter.py", line 1486, in __call__
    return self.func(*args)
  File "/data/josem/work/devel/scipion/pyworkflow/gui/text.py", line 215, in openFile
    self.openPath(self.selection)
  File "/data/josem/work/devel/scipion/pyworkflow/gui/text.py", line 225, in openPath
    subprocess.Popen(pw.getScipionScript(), ['browser', 'dir', dpath])
  File "/data/josem/work/devel/scipion/software/lib/python2.7/subprocess.py", line 659, in __init__
    raise TypeError("bufsize must be an integer")
TypeError: bufsize must be an integer

This issue can be address in PR #1182

**Comment by yaizar** [comment]
Just a note, this doesn't work when the path is a folder. Paths to files open OK (I tried a movie and a text file).

**Comment by yaizar** [comment]
@pconesa : I added the fix to pr #1182 as @delarosatrevin suggested (bug was a mix of a wrong call to subprocess.popen in ad6731a + I guess an outdated way to open the browser)

**Comment by delarosatrevin** [comment]
@yaizar Could we close this bug after you fix?
