### ISSUE TITLE
join ctf sets failing

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#1194]
I have a rather weird error in branch 1.1.1. Both inputs look fine, however join fails.
```
00011:   STARTED: createOutputStep, step 1
00012:     2017-09-07 11:17:04.565611
00013:   Traceback (most recent call last):
00014:     File "/lmb/home/gsharov/soft/scipion/pyworkflow/protocol/protocol.py", line 182, in run
00015:       self._run()
00016:     File "/lmb/home/gsharov/soft/scipion/pyworkflow/protocol/protocol.py", line 228, in _run
00017:       resultFiles = self._runFunc()
00018:     File "/lmb/home/gsharov/soft/scipion/pyworkflow/protocol/protocol.py", line 224, in _runFunc
00019:       return self._func(*self._args)
00020:     File "/lmb/home/gsharov/soft/scipion/pyworkflow/em/protocol/protocol_sets.py", line 161, in createOutputStep
00021:       outputSet.append(newObj)
00022:     File "/lmb/home/gsharov/soft/scipion/pyworkflow/object.py", line 1151, in append
00023:       self._insertItem(item)
00024:     File "/lmb/home/gsharov/soft/scipion/pyworkflow/object.py", line 1155, in _insertItem
00025:       self._getMapper().insert(item)
00026:     File "/lmb/home/gsharov/soft/scipion/pyworkflow/mapper/sqlite.py", line 729, in insert
00027:       *obj.getObjDict().values())
00028:     File "/lmb/home/gsharov/soft/scipion/pyworkflow/mapper/sqlite.py", line 1119, in insertObject
00029:       self.executeCommand(self.INSERT_OBJECT, args)
00030:   ProgrammingError: Incorrect number of bindings supplied. The current statement uses 27, and there are 28 supplied.
00031:   Protocol failed: Incorrect number of bindings supplied. The current statement uses 27, and there are 28 supplied.
00032:   FAILED: createOutputStep, step 1
00033:     2017-09-07 11:17:05.065214
00034:   ------------------- PROTOCOL FAILED (DONE 1/1)
```

**Comment by delarosatrevin** [comment]
Does both sets have the same number of columns? We need to make the join more robust when there is a mismatching of the number of columns...I have done some workaround for set of particles...but still fails for some cases.

**Comment by azazellochg** [comment]
ah, you are right, this is the problem.
