### ISSUE TITLE
facilities-devel: generate html report in background

### ISSUE THREAD

**Issue by rmarabini** [I2PC/scipion#1213]
monitor summary -> html report

If you press the button "HTML report" and you have (as is my case) 1000 processed movies the protocol will process the 1000 movies BEFORE returning scipion control. This action takes a very looooooong time (enough to write 4 new issues, check the mail and do many other things). After clicking "html report" you should get Scipion control back and if creating the files is going to take a long while the user should be warned

**Comment by rmarabini** [comment]
It just finish with an error ;-(

1 images, processing 0-0 stepping by 1
1 images
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/local/scipion/software/lib/python2.7/lib-tk/Tkinter.py", line 1486, in __call__
    return self.func(*args)
  File "/usr/local/scipion/pyworkflow/em/viewer_monitor_summary.py", line 172, in _generateHTML
    reportPath = reportHtml.generate(self.protocol.isFinished())
  File "/usr/local/scipion/pyworkflow/em/protocol/monitors/report_html.py", line 196, in generate
    'shift', relPath=reportDir)
  File "/usr/local/scipion/pyworkflow/em/protocol/monitors/report_html.py", line 99, in generateReportImages
    pwutils.copyFile(imgPath, targetDir)
  File "/usr/local/scipion/pyworkflow/utils/path.py", line 222, in copyFile
    shutil.copy(source, dest)
  File "/usr/local/scipion/software/lib/python2.7/shutil.py", line 119, in copy
    copyfile(src, dst)
  File "/usr/local/scipion/software/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: u'/home/carmen/ScipionUserData/projects/em15997/Runs/000076_ProtMotionCorr/extra/FoilHole_18363800_Data_18360230_18360231_20170919_0406_Fractions_global_shifts.png'
