### ISSUE TITLE
scipion test tests.em.workflows.test_workflow_xmipp_rct

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion#1278]
Fails on buildbot
facilities branch.

**Comment by pconesa** [comment]
With the new streaming refactoring this has been broken:
00009:   Traceback (most recent call last):
00010:     File "/home/buildbot-slave/data/slave/release11-facilities_Workflows_Tests/build/pyworkflow/protocol/protocol.py", line 182, in run
00011:       self._run()
00012:     File "/home/buildbot-slave/data/slave/release11-facilities_Workflows_Tests/build/pyworkflow/protocol/protocol.py", line 1093, in _run
00013:       self._insertAllSteps()  # Define steps for execute later
00014:     File "/home/buildbot-slave/data/slave/release11-facilities_Workflows_Tests/build/pyworkflow/em/packages/xmipp3/protocol_extract_particles_pairs.py", line 183, in _insertAllSteps
00015:       prerequisites=localDeps))
00016:     File "/home/buildbot-slave/data/slave/release11-facilities_Workflows_Tests/build/pyworkflow/protocol/protocol.py", line 779, in _insertFunctionStep
00017:       "not member of the protocol" % funcName)
00018:   Exception: Protocol._insertFunctionStep: 'extractParticlesStep' function is not member of the protocol

extractParticlesStep no longer exists.
