### ISSUE TITLE
unsupported hash type md5 when running scipion

### ISSUE THREAD

**Issue by julozi** [I2PC/scipion#1417]
Hi all,

I have installed scipion 1.2.beta from sources on Debian 9 and I get the following python error when I try to start it after install :

    Scipion V1.2.beta (26-12-2017) Caligula

    python  /shared/software/scipion/dev/pyworkflow/apps/pw_manager.py
    ERROR:root:code for hash md5 was not found.
    Traceback (most recent call last):
      File "/shared/software/scipion/dev/software/lib/python2.7/hashlib.py", line 139, in <module>
        globals()[__func_name] = __get_hash(__func_name)
      File "/shared/software/scipion/dev/software/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
        raise ValueError('unsupported hash type ' + name)
    ValueError: unsupported hash type md5
    ERROR:root:code for hash sha1 was not found.
    Traceback (most recent call last):
      File "/shared/software/scipion/dev/software/lib/python2.7/hashlib.py", line 139, in <module>
        globals()[__func_name] = __get_hash(__func_name)
      File "/shared/software/scipion/dev/software/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
        raise ValueError('unsupported hash type ' + name)
    ValueError: unsupported hash type sha1
    ERROR:root:code for hash sha224 was not found.
    Traceback (most recent call last):
      File "/shared/software/scipion/dev/software/lib/python2.7/hashlib.py", line 139, in <module>
        globals()[__func_name] = __get_hash(__func_name)
      File "/shared/software/scipion/dev/software/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
        raise ValueError('unsupported hash type ' + name)
    ValueError: unsupported hash type sha224
    ERROR:root:code for hash sha256 was not found.
    Traceback (most recent call last):
      File "/shared/software/scipion/dev/software/lib/python2.7/hashlib.py", line 139, in <module>
        globals()[__func_name] = __get_hash(__func_name)
      File "/shared/software/scipion/dev/software/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
        raise ValueError('unsupported hash type ' + name)
    ValueError: unsupported hash type sha256
    ERROR:root:code for hash sha384 was not found.
    Traceback (most recent call last):
      File "/shared/software/scipion/dev/software/lib/python2.7/hashlib.py", line 139, in <module>
        globals()[__func_name] = __get_hash(__func_name)
      File "/shared/software/scipion/dev/software/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
        raise ValueError('unsupported hash type ' + name)
    ValueError: unsupported hash type sha384
    ERROR:root:code for hash sha512 was not found.
    Traceback (most recent call last):
      File "/shared/software/scipion/dev/software/lib/python2.7/hashlib.py", line 139, in <module>
        globals()[__func_name] = __get_hash(__func_name)
      File "/shared/software/scipion/dev/software/lib/python2.7/hashlib.py", line 91, in __get_builtin_constructor
        raise ValueError('unsupported hash type ' + name)
    ValueError: unsupported hash type sha512
    Traceback (most recent call last):
      File "/shared/software/scipion/dev/pyworkflow/apps/pw_manager.py", line 32, in <module>
        from pyworkflow.gui.project import ProjectManagerWindow
      File "/shared/software/scipion/dev/pyworkflow/gui/project/__init__.py", line 27, in <module>
        from project import ProjectManagerWindow, ProjectWindow
      File "/shared/software/scipion/dev/pyworkflow/gui/project/project.py", line 45, in <module>
        from pyworkflow.manager import Manager
      File "/shared/software/scipion/dev/pyworkflow/manager.py", line 33, in <module>
        from project import Project
      File "/shared/software/scipion/dev/pyworkflow/project.py", line 38, in <module>
        import pyworkflow.em as em
      File "/shared/software/scipion/dev/pyworkflow/em/__init__.py", line 37, in <module>
        from protocol import *
      File "/shared/software/scipion/dev/pyworkflow/em/protocol/__init__.py", line 45, in <module>
        from protocol_classes_consensus import ProtClassesConsensus, ViewerClassesConsensus
      File "/shared/software/scipion/dev/pyworkflow/em/protocol/protocol_classes_consensus.py", line 36, in <module>
        from pyworkflow.em.viewer import DataView
      File "/shared/software/scipion/dev/pyworkflow/em/viewer.py", line 42, in <module>
        from pyworkflow.gui.matplotlib_image import ImageWindow
      File "/shared/software/scipion/dev/pyworkflow/gui/matplotlib_image.py", line 42, in <module>
        from matplotlib.figure import Figure
      File "/shared/software/scipion/dev/software/lib/python2.7/site-packages/matplotlib-1.3.1-py2.7-linux-x86_64.egg/matplotlib/figure.py", line 34, in <module>
        import matplotlib.colorbar as cbar
      File "/shared/software/scipion/dev/software/lib/python2.7/site-packages/matplotlib-1.3.1-py2.7-linux-x86_64.egg/matplotlib/colorbar.py", line 31, in <module>
        import matplotlib.contour as contour
      File "/shared/software/scipion/dev/software/lib/python2.7/site-packages/matplotlib-1.3.1-py2.7-linux-x86_64.egg/matplotlib/contour.py", line 22, in <module>
        import matplotlib.texmanager as texmanager
      File "/shared/software/scipion/dev/software/lib/python2.7/site-packages/matplotlib-1.3.1-py2.7-linux-x86_64.egg/matplotlib/texmanager.py", line 46, in <module>
        from hashlib import md5
    ImportError: cannot import name md5

I had the same issue during installation when scipion was compiling numpy. I managed to get around it by running the `python setup.py install` manually for numpy using the python installed by scipion.

My guess is that some environment setting done by scipion is messing up its python and that it can't find the openssl lib from the system anymore. If I run the python installed by scipion manually, hashlib is working just fine.
Do you have any idea how I could fix this ?

Thanks for your help,

Julien

**Comment by azazellochg** [comment]
Hi @julozi , I think I had this issue before but can't remember the way I fixed it. Could you try to install latest python 2.7.x instead of the one that Scipion distributes?

**Comment by julozi** [comment]
Hi @azazellochg, thanks for your help.
I have rebuilt scipion from scratch forcing Python 2.7.14 and everything is now working fine !

Maybe the package repository should be upgraded for Python.

Thanks a lot,

Julien

**Comment by azazellochg** [comment]
@julozi great! updating python is definitely on a to-do list.
