### ISSUE TITLE
Can't view relion's 2D class average in showj viewer

### ISSUE THREAD

**Issue by phonchi** [I2PC/scipion#1430]
I am following the mix and match tutorial, and when I finish the relion 2D classification I can not see the class average as shown in the following figure:

![problem_scipion_relion](https://user-images.githubusercontent.com/11373055/35031440-eac316f4-fb9d-11e7-8b88-efcfc9a41d2e.png)

and the console shows the following error when I click the image:

```
java.lang.IllegalArgumentException: Path 'null' doesn't exists.
	at xmipp.viewer.models.MetadataGalleryTableModel.openXmippImageWindow(MetadataGalleryTableModel.java:134)
	at xmipp.viewer.models.MetadataGalleryTableModel.handleDoubleClick(MetadataGalleryTableModel.java:279)
	at xmipp.viewer.windows.GalleryJFrame.tableMouseClicked(GalleryJFrame.java:1464)
	at xmipp.viewer.windows.GalleryJFrame$9.mouseReleased(GalleryJFrame.java:568)
	at java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:290)
	at java.awt.Component.processMouseEvent(Component.java:6533)
	at javax.swing.JComponent.processMouseEvent(JComponent.java:3324)
	at java.awt.Component.processEvent(Component.java:6298)
	at java.awt.Container.processEvent(Container.java:2236)
	at java.awt.Component.dispatchEventImpl(Component.java:4889)
	at java.awt.Container.dispatchEventImpl(Container.java:2294)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4888)
	at java.awt.LightweightDispatcher.processMouseEvent(Container.java:4525)
	at java.awt.LightweightDispatcher.dispatchEvent(Container.java:4466)
	at java.awt.Container.dispatchEventImpl(Container.java:2280)
	at java.awt.Window.dispatchEventImpl(Window.java:2746)
	at java.awt.Component.dispatchEvent(Component.java:4711)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:90)
	at java.awt.EventQueue$4.run(EventQueue.java:731)
	at java.awt.EventQueue$4.run(EventQueue.java:729)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:80)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

I am in master (building from source), and when I am using the binary version V1.2.beta_26-12-2017_linux64.tgz it works well.

Or should I try to build from source using the newest branch (is it https://github.com/I2PC/scipion/tree/release-1.1.facilities-fixes?)

Any suggestions about the problem? Thanks in advance!

**Comment by azazellochg** [comment]
Hi @phonchi !
Hm, it should work in master as well. Did you check that relion protocol has finished properly (i.e., if you go into run's extra folder do you see all relion files? *model.star?)?

**Comment by pconesa** [comment]
@phonchi , it is the second time in 2 days someone reports this...another user is going to send us her database to explore this. I'll post our progress here.

**Comment by pconesa** [comment]
Just to check:
1.- In the window with the red X
2.- Click on the button
![image](https://user-images.githubusercontent.com/785633/35042145-a9e0daba-fb87-11e7-8fd6-8ee129fc9a4c.png)
3.- Press "Ctrl+R" or Click on "display">Rended images
What do you get in the _representative._filename column?
Is it empty?

**Comment by phonchi** [comment]
Yes it's empty following the given procedure.

**Comment by pconesa** [comment]
Thanks @phonchi , use relion 2d classification very frequently and actually I've done this today to see if I can reproduce it... it works fine. I might need to follow the tutorial to reproduce it.

**Comment by pconesa** [comment]
Hi @ponchi, I looked into this and in other user's case, for some reason the "output generation" worked similarly, maybe due to some values un the metadata (inf). There is an issue. In this case, there is a partial workaround would be to:

0.- Select the relion protocol.
1.- Click on "Analyze results"
2.- Select "iteration"
3.- Enter "25" (for the iteration 25). Enter the last one you have.
4.- Click on "Show classification in Scipion"

This would generate the classes, and in my case averages appear. But without some columns, thus the "partial":
'rlnEstimatedResolution'
'rlnOverallFourierCompleteness'
'rlnClassPriorOffsetX'
'rlnClassPriorOffsetY'

This will not register the output. If you want to do so, then you can:

0.- Move to the protocol folder (cd Runs/000XXX_ProtRelionClassify2D)
1.- Back up the output, just in case: 
cp classes2D.sqlite classes2D.sqlite.orig
2.- Use the generated one:
cp extra/relion_it025_classes_scipion.sqlite classes2D.sqlite

Hope it helps.

**Comment by pconesa** [comment]
@phonchi ....could you resume your work?

**Comment by phonchi** [comment]
Sorry for the late reply, but I have switched to another branch (release-1.1.facilities-fixes).

It works fine now using this branch, thanks again for the help!
