### ISSUE TITLE
frealign fails in test_workflow_mixed.TestMixedBPV

### ISSUE THREAD

**Issue by yaizar** [I2PC/scipion#1491]
```00002:             PID: 10537
00003:         Scipion: v1.2.beta (2018-02-14) Caligula (release-1.1.facilities-devel 5efce87)
00004:      currentDir: /home/scipion/ScipionUserData/projects/TestMixedBPV
00005:      workingDir: Runs/000330_ProtFrealign
00006:         runMode: Restart
00007:             MPI: 1
00008:         threads: 4
00009:   Traceback (most recent call last):
00010:     File "/home/local/scipion/pyworkflow/protocol/protocol.py", line 186, in run
00011:       self._run()
00012:     File "/home/local/scipion/pyworkflow/protocol/protocol.py", line 1106, in _run
00013:       self._insertAllSteps()  # Define steps for execute later
00014:     File "/home/local/scipion/pyworkflow/em/packages/grigoriefflab/protocol_frealign_base.py", line 505, in _insertAllSteps
00015:       self._insertItersSteps()
00016:     File "/home/local/scipion/pyworkflow/em/packages/grigoriefflab/protocol_frealign_base.py", line 533, in _insertItersSteps
00017:       paramsDic = self._getParamsIteration(iterN)
00018:     File "/home/local/scipion/pyworkflow/em/packages/grigoriefflab/protocol_frealign_base.py", line 827, in _getParamsIteration
00019:       paramsDic['scannedPixelSize'] = acquisition.getMagnification() * imgSet.getSamplingRate() / 10000
00020:   TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'
00021:   ------------------- PROTOCOL FAILED (DONE 0/0)
```

**Comment by yaizar** [comment]
The problem is that the input particles don't have acquisition - not sure if this is an error of XmippProtExtractParticles for not setting the acquisition or if it is an error of Frealign for not saying that it expects particles with acquisition info (or even expecting acquisition at particle level)? @delarosatrevin any idea?
