### ISSUE TITLE
Continuing Relion Autorefine bug.

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion#1668]
This is from Ana Cuervo, who is betatesting release-1.2.1:

She is trying to "Resume" an auto refine, and she is getting this:
```bash
File 'Runs/004193_ProtRelionRefine3D/logs/run.stdout' doesn't exist00001:   RUNNING PROTOCOL -----------------
00002:        HostName: virgo.cnb.csic.es
00003:             PID: 16352
00004:         Scipion:  (2018-05-18)  (release-1.2.1 b6776a1)
00005:      currentDir: /home/acuervo/ScipionUserData/projects/em15997-13_20180409_1643
00006:      workingDir: Runs/004193_ProtRelionRefine3D
00007:         runMode: Restart
00008:             MPI: 3
00009:         threads: 2
00010:   Input File: Runs/003188_ProtRelionCreateMask3D/extra/mask.mrc
00011:   Output File: Runs/004193_ProtRelionRefine3D/tmp/mask.mrc
00012:   Selection method:    below
00013:   Threshold:           0
00014:   Substitution method: value
00015:   New value:           0
00016:      0/   0 sec. ............................................................
00017:   Input File: Runs/004193_ProtRelionRefine3D/tmp/mask.mrc
00018:   Selection method:    above
00019:   Threshold:           1
00020:   Substitution method: value
00021:   New value:           1
00022:      0/   0 sec. ............................................................
00023:   ** Running command: xmipp_transform_threshold -i Runs/003188_ProtRelionCreateMask3D/extra/mask.mrc -o Runs/004193_ProtRelionRefine3D/tmp/mask.mrc --select below 0 --substitute value 0
00024:   ** Running command: xmipp_transform_threshold -i Runs/004193_ProtRelionRefine3D/tmp/mask.mrc --select above 1 --substitute value 1
00025:    Starting at step: 1
00026:    Running steps
00027:   STARTED: convertInputStep, step 1
00028:     2018-06-27 10:53:33.167071
00029:   In continue mode is not necessary convert the input particles
00030:   Traceback (most recent call last):
00031:     File "/usr/local/scipion/pyworkflow/protocol/protocol.py", line 186, in run
00032:       self._run()
00033:     File "/usr/local/scipion/pyworkflow/protocol/protocol.py", line 233, in _run
00034:       resultFiles = self._runFunc()
00035:     File "/usr/local/scipion/pyworkflow/protocol/protocol.py", line 229, in _runFunc
00036:       return self._func(*self._args)
00037:     File "/usr/local/scipion/pyworkflow/em/packages/relion/protocol_base.py", line 848, in convertInputStep
00038:       if self._getRefArg():
00039:     File "/usr/local/scipion/pyworkflow/em/packages/relion/protocol_base.py", line 1231, in _getRefArg
00040:       refVols = self._getReferenceVolumes()
00041:     File "/usr/local/scipion/pyworkflow/em/packages/relion/protocol_base.py", line 1222, in _getReferenceVolumes
00042:       % inputObj.getClassName())
00043:   AttributeError: 'NoneType' object has no attribute 'getClassName'
00044:   Protocol failed: 'NoneType' object has no attribute 'getClassName'
00045:   FAILED: convertInputStep, step 1
00046:     2018-06-27 10:53:33.213165 
```
Looking at the failing code....:

```python
   def _getReferenceVolumes(self):
        """ Return a list with all input references.
        (Could be one or more volumes. ).
        """
        inputObj = self.referenceVolume.get()

        if isinstance(inputObj, em.Volume):
            return [inputObj]
        elif isinstance(inputObj, em.SetOfVolumes):
            return [vol.clone() for vol in inputObj]
        else:
            raise Exception("Invalid input reference of class: %s"
                            % inputObj.getClassName())
```
Seems she has None for referenceVolume attribute and in the else (raising exception, the inputObj.getClassName(), when inputObj == None is just exploding.

So, I do not know if having None in referenceVolume is an option and has to be considered here or the problem is that she has None in the referenceVolume?

**Comment by azazellochg** [comment]
I couldn't reproduce it by stopping a relion refine run, then making a copy and using "continue from" option. All work as expected. Reference volume cannot be None. @pconesa is it still happening?

**Comment by pconesa** [comment]
Hi @azazellochg , this happened just then. We'll try to reproduce it

**Comment by pconesa** [comment]
I'm closing this....if it happens again, I'll report it
