### ISSUE TITLE
Tree graph not working

### ISSUE THREAD

**Issue by josuegbl** [I2PC/scipion#1691]
Traceback (most recent call last):
  File "/home/josuegbl/SOFTWARE/scipion/software/lib/python2.7/lib-tk/Tkinter.py", line 1541, in __call__
    return self.func(*args)
  File "/home/josuegbl/SOFTWARE/scipion/pyworkflow/gui/project/viewprotocols.py", line 302, in _showTree
    g = self._protocol.getStepsGraph()
  File "/home/josuegbl/SOFTWARE/scipion/pyworkflow/protocol/protocol.py", line 1856, in getStepsGraph
    stepsDict[p].addChild(n)
KeyError: '9'

**Comment by pconesa** [comment]
@josuegbl, does this still happen? I tried the other day and seems to work.

**Comment by josuegbl** [comment]
It seems is working right now.... you can close this...
