### ISSUE TITLE
Problem with NMA protocol

### ISSUE THREAD

**Issue by vabrishami** [I2PC/scipion#1710]
I am trying the NMA analysis protocol in Scipion. It seems it works ok, but then there is an error generating the output (not in the final output step):

STARTED: reformatPdbOutputStep, step 4
00194:     2018-08-01 09:22:25.777632
00195:   Traceback (most recent call last):
00196:     File "/wrk/project_cryoem/apps/taito/scipion-1.2.facilities-devel/pyworkflow/protocol/protocol.py", line 186, in run
00197:       self._run()
00198:     File "/wrk/project_cryoem/apps/taito/scipion-1.2.facilities-devel/pyworkflow/protocol/protocol.py", line 233, in _run
00199:       resultFiles = self._runFunc()
00200:     File "/wrk/project_cryoem/apps/taito/scipion-1.2.facilities-devel/pyworkflow/protocol/protocol.py", line 229, in _runFunc
00201:       return self._func(*self._args)
00202:     File "/wrk/project_cryoem/apps/taito/scipion-1.2.facilities-devel/pyworkflow/em/packages/xmipp3/nma/protocol_nma.py", line 190, in reformatPdbOutputStep
00203:       fhIn = open('diagrtb.eigenfacs')
00204:   IOError: [Errno 2] No such file or directory: 'diagrtb.eigenfacs'
00205:   Protocol failed: [Errno 2] No such file or directory: 'diagrtb.eigenfacs'
00206:   FAILED: reformatPdbOutputStep, step 4
00207:     2018-08-01 09:22:26.822747
00208:   ------------------- PROTOCOL FAILED (DONE 4/8)

I will try to check the code, but any idea?

**Comment by vabrishami** [comment]
This is because I have too many atoms. So I close it.
