### ISSUE TITLE
test relion TestRelionSubtract fails (scipion pluginized) 

### ISSUE THREAD

**Issue by josuegbl** [I2PC/scipion#1729]
One of the test that @delarosatrevin reported as OK, is failing in my hands.... I executed the line: 
./scipion test relion.tests.test_protocols_relion.TestRelionSubtract. I installed a fresh scipion and set the plugins in the PYTHONPATH. the error when execute the test was:

Scipion  (2018-08-17)  (devel-pluginization f07516d)

>>>>> python  scripts/run_tests.py relion.tests.test_protocols_relion.TestRelionSubtract
Xmipp binaries not found. Ghost active.....BOOOOOO!
  > See scipion install --list to install Xmipp. 
/home/josuegbl/SOFTWARE/scipion-pluginization/software/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
Running tests....

 >>> 'import xmipp' is deprecated for the xmipp binding:
  File "scripts/run_tests.py", line 296, in <module>
    Tester().main()
  File "scripts/run_tests.py", line 95, in main
    testsDict['tests'].addTests(testLoader.loadTestsFromName(t))
  File "/home/josuegbl/SOFTWARE/scipion-pluginization/software/lib/python2.7/unittest/loader.py", line 91, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
  File "/home/josuegbl/SOFTWARE/scipion-em-plugins/scipion-em-relion/relion/tests/__init__.py", line 4, in <module>
    from .test_workflow_relion import *
  File "/home/josuegbl/SOFTWARE/scipion-em-plugins/scipion-em-relion/relion/tests/test_workflow_relion.py", line 32, in <module>
    from xmipp3.protocols import XmippProtPreprocessMicrographs
  File "/home/josuegbl/SOFTWARE/scipion-em-plugins/scipion-em-xmipp/xmipp3/__init__.py", line 32, in <module>
    from .base import *
  File "/home/josuegbl/SOFTWARE/scipion-em-plugins/scipion-em-xmipp/xmipp3/base.py", line 39, in <module>
    import xmipp
  File "/home/josuegbl/SOFTWARE/scipion-pluginization/pyworkflow/em/xmipp-ghost/xmipp.py", line 33, in <module>
    traceback.print_stack()
 > Please change 'import xmipp' to 'import xmippLib' 

('Creating project at: ', '/home/josuegbl/ScipionUserData/projects/TestRelionSubtract/project.sqlite')
Warning: IMAGIC_ROOT directory (  ) does not contain openmpi folder.
No MPI support will be enabled.
Warning: IMAGIC_ROOT directory (  ) does not contain openmpi folder.
No MPI support will be enabled.
>>>> python /home/josuegbl/SOFTWARE/scipion-pluginization/scipion testdata --download relion_tutorial

Scipion  (2018-08-17)  (devel-pluginization f07516d)

>>>>> python  scripts/sync_data.py --download relion_tutorial
Selected datasets: relion_tutorial
Local copy of dataset relion_tutorial detected.
Checking for updates...
Verifying MD5s...
...done. Updated files: 0
** Running command: 'python /home/josuegbl/SOFTWARE/scipion-pluginization/scipion runprotocol pw_protocol_run.py "/home/josuegbl/ScipionUserData/projects/TestRelionSubtract" "Runs/000002_ProtImportParticles/logs/run.db" 2'

Scipion  (2018-08-17)  (devel-pluginization f07516d)

>>>>> python  /home/josuegbl/SOFTWARE/scipion-pluginization/pyworkflow/apps/pw_protocol_run.py "/home/josuegbl/ScipionUserData/projects/TestRelionSubtract" "Runs/000002_ProtImportParticles/logs/run.db" "2"
Xmipp binaries not found. Ghost active.....BOOOOOO!
  > See scipion install --list to install Xmipp. 
/home/josuegbl/SOFTWARE/scipion-pluginization/software/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')

 >>> 'import xmipp' is deprecated for the xmipp binding:
  File "/home/josuegbl/SOFTWARE/scipion-pluginization/pyworkflow/apps/pw_protocol_run.py", line 49, in <module>
    runProtocolMain(projPath, dbPath, protId)
  File "/home/josuegbl/SOFTWARE/scipion-pluginization/pyworkflow/protocol/protocol.py", line 1903, in runProtocolMain
    protocol = getProtocolFromDb(projectPath, protDbPath, protId, chdir=True)
  File "/home/josuegbl/SOFTWARE/scipion-pluginization/pyworkflow/protocol/protocol.py", line 1974, in getProtocolFromDb
    loadAllConfig=False)
  File "/home/josuegbl/SOFTWARE/scipion-pluginization/pyworkflow/project.py", line 248, in load
    self._loadDb(dbPath)
  File "/home/josuegbl/SOFTWARE/scipion-pluginization/pyworkflow/project.py", line 297, in _loadDb
    self.mapper = self.createMapper(absDbPath)
  File "/home/josuegbl/SOFTWARE/scipion-pluginization/pyworkflow/project.py", line 216, in createMapper
    classesDict.update(em.Domain.getProtocols())
  File "/home/josuegbl/SOFTWARE/scipion-pluginization/pyworkflow/plugin.py", line 156, in getProtocols
    return cls.__getSubclasses('protocols', cls._protocolClass)
  File "/home/josuegbl/SOFTWARE/scipion-pluginization/pyworkflow/plugin.py", line 138, in __getSubclasses
    for pluginName, plugin in cls.getPlugins().iteritems():
  File "/home/josuegbl/SOFTWARE/scipion-pluginization/pyworkflow/plugin.py", line 113, in getPlugins
    importlib.import_module(name)
  File "/home/josuegbl/SOFTWARE/scipion-pluginization/software/lib/python2.7/importlib/__init__.py", line 37, in import_module
    __import__(name)
  File "/home/josuegbl/SOFTWARE/scipion-em-plugins/scipion-em-xmipp/xmipp3/__init__.py", line 32, in <module>
    from .base import *
  File "/home/josuegbl/SOFTWARE/scipion-em-plugins/scipion-em-xmipp/xmipp3/base.py", line 39, in <module>
    import xmipp
  File "/home/josuegbl/SOFTWARE/scipion-pluginization/pyworkflow/em/xmipp-ghost/xmipp.py", line 33, in <module>
    traceback.print_stack()
 > Please change 'import xmipp' to 'import xmippLib' 

>>> ERROR running protocol from relion auto-refine
[   FAILED ] TestRelionSubtract.test_subtract

Traceback (most recent call last):
  File "/home/josuegbl/SOFTWARE/scipion-pluginization/software/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/josuegbl/SOFTWARE/scipion-em-plugins/scipion-em-relion/relion/tests/test_protocols_relion.py", line 395, in test_subtract
    self.launchProtocol(protParts)
  File "/home/josuegbl/SOFTWARE/scipion-pluginization/pyworkflow/tests/tests.py", line 106, in launchProtocol
    raise Exception("ERROR: Protocol not finished")
Exception: ERROR: Protocol not finished

**Comment by josuegbl** [comment]
Thanks for your comments. Regarding the problems that you have identified:
1- a warning is just that: warn that there is something wrong but the program/package should be executed and work properly, at least in part. So, I dont understand if scipion doesn't works without xmipp, you just warns that "Xmipp binaries not found. Ghost active".

2- I think that you must had assumed that "git pull" solution were tried for me before open this issue. If you say that this is fixed in some branch/repo would be better if you could give me the address  in which this issue was fixed.

**Comment by dmaluenda** [comment]
Hi Josue, 

1. Scipion can run without the xmipp (via ghost), however Relion uses metadata labels coming from the xmipp binding. Thus, probably the problem is there. Following the trace, it seems that scipion runs but the import particles protocol is failing. But here the trace is not giving enough info since is just _raise Exception("ERROR: Protocol not finished")_. Could you please open the project and get the trace for that protocol? (or from the `Runs/000002_ProtImportParticles/logs/run.log`)

2. The update of the xmipp plugin is not the crucial point here, but I realized that it is not in the most recent version and I warned, just in case. You can find the last version of the xmipp plugin [here](https://github.com/I2PC/scipion-em-xmipp/tree/devel).

Thanks!

**Comment by pconesa** [comment]
Just one thing, the xmipp ghost is just enough to cheat scipion when there is no xmipp. It is not "ghosting" all xmipp binding, now renamed to xmippLib. Thus RELION labels are not I. The ghost and fails.

**Comment by josuegbl** [comment]
Ok, you are right, relion labels are not in the ghost, but I executed also ctffind4 test and its failing too. @dmaluenda below you have the requested log:



run.log:
2018-08-17 15:54:47,943 INFO:  [32mRUNNING PROTOCOL -----------------[0m
2018-08-17 15:54:48,005 INFO:       HostName: rosalind
2018-08-17 15:54:48,005 INFO:            PID: 27468
2018-08-17 15:54:48,005 INFO:        Scipion:  (2018-08-17)  (devel-pluginization f07516d)
2018-08-17 15:54:48,006 INFO:     currentDir: /home/josuegbl/ScipionUserData/projects/TestRelionSubtract
2018-08-17 15:54:48,006 INFO:     workingDir: Runs/000002_ProtImportParticles
2018-08-17 15:54:48,006 INFO:        runMode: Continue
2018-08-17 15:54:48,006 INFO:            MPI: 1
2018-08-17 15:54:48,006 INFO:        threads: 1
2018-08-17 15:54:48,179 INFO:  [32m------------------- PROTOCOL FAILED (DONE 0/0)[0m


run.stdout:
[32mRUNNING PROTOCOL -----------------[0m
     HostName: rosalind
          PID: 27468
      Scipion:  (2018-08-17)  (devel-pluginization f07516d)
   currentDir: /home/josuegbl/ScipionUserData/projects/TestRelionSubtract
   workingDir: Runs/000002_ProtImportParticles
      runMode: Continue
          MPI: 1
      threads: 1
Xmipp binaries not found. Ghost active.....BOOOOOO!
  > See scipion install --list to install Xmipp. 
Traceback (most recent call last):
  File "/home/josuegbl/SOFTWARE/scipion-pluginization/pyworkflow/protocol/protocol.py", line 186, in run
    self._run()
  File "/home/josuegbl/SOFTWARE/scipion-pluginization/pyworkflow/protocol/protocol.py", line 1125, in _run
    'Protocol.run: Validation errors:\n' + '\n'.join(errors))
Exception: Protocol.run: Validation errors:
'NoneType' object has no attribute 'read'
[32m------------------- PROTOCOL FAILED (DONE 0/0)[0m

**Comment by josuegbl** [comment]
Im closing this cause all imports depends on xmipp, so xmipp must be installed.

**Comment by josuegbl** [comment]
Thanks @dmaluenda but I had already realized by myself.
