### ISSUE TITLE
Pending update when register Class2D and Particles in 2D classify

### ISSUE THREAD

**Issue by phonchi** [I2PC/scipion#1744]
Dear developers:
I am trying to integrate the ISAC2 protocol from SPHIRE and since ISAC will drop unstable images from input particle set, so I face some problems when trying to create the output. 

The following is my code snippet related to creating the output:

```
        from pyworkflow.em.protocol import ProtClassify2D, SetOfClasses2D
	from pyworkflow.protocol.params import (PointerParam, BooleanParam,
											FloatParam, IntParam, Positive, StringParam)
	from pyworkflow.em.packages.relion.convert import (writeSetOfParticles,readSetOfParticles,
													   getVersion, relionToLocation)
	from pyworkflow.em.packages.xmipp3.convert import xmippToLocation, rowToAlignment

	class ProtISAC(ProtClassify2D):
	
	......
	
	
	def createOutputStep(self):
        
        # Here I delete the unstable particles from star file and add the class number info
        classes = np.load(self._getPath()+"/classes.npy")
        classes = classes.tolist()
        ids = []
        with open(self._getFileName("processfile"), 'r') as infile:
            for line in infile:
                ids.append(line.split()[0])
       
        with open(self._getFileName('input_particles_m2'), 'r') as input_file, open(self._getFileName('input_particles_m3'), 'w') as output_file:
            j = 0 
            i = 0 
            k = 0
            for line in input_file:
                if line.startswith("_rln"):
                    output_file.write(line)
                    i = 1
                elif i == 0:
                    output_file.write(line)
                elif j == 0:
                    output_file.write('_rlnClassNumber\n')
                    if str(k) in ids:
                        iid = self._find_in_list_of_list(classes, k)
                        output_file.write(line.rstrip()+' '+str(iid+1)+'\n')
                    j = 1
                else:
                    k = k +1
                    if str(k) in ids:
                        iid = self._find_in_list_of_list(classes, k)
                        output_file.write(line.rstrip()+' '+str(iid+1)+'\n')

        # Trying to update the class information
        inputParticles = self._createSetOfParticles()
        readSetOfParticles(self._getFileName('input_particles_m3'), inputParticles, alignType=em.ALIGN_2D)       
        classes2DSet = self._createSetOfClasses2D(inputParticles)
        self._fillClassesFromLevel(classes2DSet)
  
        self._defineOutputs(outputClasses=classes2DSet)
        self._defineSourceRelation(self.inputParticles, classes2DSet)


    def _loadClassesInfo(self, filename):
        """ Read some information about the produced 2D classes
        from the metadata file.
        """
        self._classesInfo = {}  # store classes info, indexed by class id

        mdClasses = md.MetaData(filename)

        for classNumber, row in enumerate(md.iterRows(mdClasses)):
            index, fn = xmippToLocation(row.getValue(md.MDL_IMAGE))
            # Store info indexed by id, we need to store the row.clone() since
            # the same reference is used for iteration
            self._classesInfo[classNumber + 1] = (index, fn, row.clone())
        self._numClass = index

    def _find_in_list_of_list(self, mylist, char):
        for sub_list in mylist:
            if char in sub_list:
                return (mylist.index(sub_list))
        return -1

    def _fillClassesFromLevel(self, clsSet):
        """ Create the SetOfClasses2D from a given iteration. """
            #xmpMd = self._getFileName("class_average")
        xmpMd = self._getFileName("input_particles_m3") #the particle with orientation parameters (all_parameters)

        clsSet.classifyItems(updateItemCallback=self._updateParticle,
                                 updateClassCallback=self._updateClass,
                                 itemDataIterator=md.iterRows(xmpMd,
                                                          sortByLabel=md.MDL_ITEM_ID)) # relion style
    # --------------------------- INFO functions -------------------------------
    def _validate(self):
        """ Should be overriden in subclasses to 
        return summary message for NORMAL EXECUTION. 
        """
        validateMsgs = []
        return validateMsgs
    
    # --------------------------- UTILS functions ------------------------------
    def _updateParticle(self, item, row):
        item.setClassId(row.getValue(md.MDL_REF))
        item.setTransform(rowToAlignment(row, em.ALIGN_2D))

    def _updateClass(self, item):
        classId = item.getObjId()

        if classId in self._classesInfo:
            index, fn, _ = self._classesInfo[classId]
            item.setAlignment2D()
            rep = item.getRepresentative()
            rep.setLocation(index, fn)
            rep.setSamplingRate(self.inputParticles.get().getSamplingRate())
```

The protocol has finished sucessfully, however, there is runtime error as follows:
```
ERROR: invalid literal for int() with base 10: 'Pending update', tries=3
Traceback (most recent call last):
  File "/home/users/scipion-1.3/scipion/pyworkflow/project.py", line 504, in _updateProtocol
    protocol.getObjId())
  File "/home/users/scipion-1.3/scipion/pyworkflow/protocol/protocol.py", line 1903, in getProtocolFromDb
    protocol = project.getProtocol(protId)
  File "/home/users/scipion-1.3/scipion/pyworkflow/project.py", line 954, in getProtocol
    protocol = self.mapper.selectById(protId)
  File "/home/users/scipion-1.3/scipion/pyworkflow/mapper/sqlite.py", line 187, in selectById
    self.fillObject(obj, objRow)
  File "/home/users/scipion-1.3/scipion/pyworkflow/mapper/sqlite.py", line 245, in fillObject
    self.fillObjectWithRow(childObj, childRow)
  File "/home/users


/scipion-1.3/scipion/pyworkflow/mapper/sqlite.py", line 214, in fillObjectWithRow
    objValue = self.selectById(int(objValue))
ValueError: invalid literal for int() with base 10: 'Pending update'
```

and there is no SetOfClasses2D in the output.

What might be the problem about this error or how to debug?
The attachment is the star file and sql file
[Logs.zip](https://github.com/I2PC/scipion/files/2336905/Logs.zip)
Any suggestion would be appreciated. Thanks in advance!

**Comment by pconesa** [comment]
Hi @phonchi, first thank you for contributing. Probably the droped images are somehow causing the problem. 

I don't see any scipion fork...is it possible to use your code. Do you have any test, even if it fails it would be the quickest way to have a look. Otherwise we'll try to guess what is going on

**Comment by phonchi** [comment]
Thanks for the reply!

Currently, I collect the unstable particles of ISAC2 into an additional class (so that the particle numbers of input and output are equal). I am able to create the results as follows:

```
# **************************************************************************
# *
# **************************************************************************

from glob import glob
from scipy import io
from subprocess import check_call
import sys
import numpy as np 
import os
import shutil
import pyworkflow.em as em
import pyworkflow.em.metadata as md
from pyworkflow.utils.path import moveFile

from pyworkflow.em.protocol import ProtClassify2D, SetOfClasses2D
from pyworkflow.protocol.params import (PointerParam, BooleanParam,
                                        FloatParam, IntParam, Positive, StringParam)
from pyworkflow.em.packages.relion.convert import (writeSetOfParticles,readSetOfParticles,
                                                   getVersion, relionToLocation)
from pyworkflow.em.packages.xmipp3.convert import xmippToLocation, rowToAlignment

class ProtISAC(ProtClassify2D):
    """ Wrapper to ISAC2 program.
    """
    _label = 'perform ISAC2'
    
    def __init__(self, **args):
        ProtClassify2D.__init__(self, **args)
        if self.numberOfMpi.get() < 2:
            self.numberOfMpi.set(2)
    
    def _defineFileNames(self):
        """ Centralize how files are called within the protocol. """
        myDict = {
                  'input_particles': self._getPath('input_particles.star'),
                  'input_particles_m': self._getPath('input_particles_m.star'),
                  'input_particles_m2': self._getPath('input_particles_m2.star'),
                  'input_particles_m3': self._getPath('input_particles_m3.star'),
                  'class_average': self._getPath() + '/Class2D/class_averages.hdf',
                  'class_average_b': self._getPath() + '/Class_Beau/class_averages.hdf',
                  'processfile': self._getPath() + '/Class2D/processed_images.txt',
                  'notprocessfile': self._getPath() + '/Class2D/not_processed_images.txt',
                  'params': self._getPath()+'/Class2D/all_parameters.txt',
                  'params2': self._getPath()+'/Class2D/2dalignment/initial2Dparams.txt',
                  'out_particles': self._getPath() + '/Particles/sphire_stack.hdf',
                  'out_class': self._getPath() + '/output.hdf',
                  'out_db': "bdb:"+self._getPath() + '/Particles#stack',
                  'isac_dir': self._getPath() + '/Class2D'
                  }
        self._updateFilenamesDict(myDict)
    
    # --------------------------- DEFINE param functions -----------------------
    def _defineParams(self, form):
        form.addSection(label='Input')
        form.addParam('inputParticles', PointerParam,
                      pointerClass='SetOfParticles',
                      label="Input particles", important=True,
                      help='Select the input images from the project.')
        form.addParam('numberOfImages', IntParam, default=100, validators=[Positive],
                      label='Image per Group',
                      help='Number of images to be generated for a group')

        form.addParam('boxsize', IntParam, default=0, label='Particle Box Size', important=True, help='The expected particle box size')
        # Radius
        form.addParam('radius', IntParam, default=40, validators=[Positive],
                      label='Particle radius',
                      help='The original radius of particle')
                
        form.addParam('target_radius', IntParam, default=29, validators=[Positive],
                      label='Resize particle radius',
                      help='Target resize particle radius')
        
        form.addParam('target_box_size', IntParam, default=76, validators=[Positive],
                       label='Resize box size',
                       help='Target resize box size')
        form.addParam('doCTF', BooleanParam, default=False, important=True,
                       label='Do CTF correction?',
                       help='If set to True, we must provide CTF information')
        form.addParam('doPhase', BooleanParam, default=False, important=True,
                       label='Is the data collected by phase plate??',
                       help='If set to True, we must provide phase information')

        form.addParam('thld_err', StringParam, default="0.7", important=True,
                       label='Threshold ',
                       help='With increased number of particles per class or in case you expect a high degree\
                       of flexibility in your particle, you should set a higher threshold value (forexample 1.7)')
        form.addParam('doBeautify', BooleanParam, default=False, important=True,
                      label='Beautify ',
                      help='adjust to analytic model?')
        form.addParam('pixelsize', StringParam, default="1", important=True,
                      label='pixelsize ',
                      help='pixel size')
        form.addParam('restart', IntParam, default=-1,
                       label='Restart iteration',
                       help='Continue from which iteration')
        form.addParallelSection(threads=1, mpi=2)
    
    # --------------------------- INSERT steps functions -----------------------
    def _insertAllSteps(self):
        self._defineFileNames()
        objId = self.inputParticles.get().getObjId()
        self._insertFunctionStep("convertInputStep", objId)
        self._insertFunctionStep('processStep')
        self._insertFunctionStep('createOutputStep')

    # --------------------------- STEPS functions ------------------------------
    def convertInputStep(self, particlesId):
        """ Create the input file in STAR format as expected by Relion.
        If the input particles comes from Relion, just link the file. 
        """
        imgSet = self.inputParticles.get()
        # Create links to binary files and write the relion .star file
        writeSetOfParticles(imgSet, self._getFileName('input_particles'), outputDir=self._getExtraPath(), fillMagnification=True, RemoveClassAngle=True)

        parti = False
        index = 0

        with open(self._getFileName('input_particles'), 'r') as input_file, open(self._getFileName('input_particles_m'), 'w') as output_file:
            i = 1
            for line in input_file:
                if line.startswith(" _rlnCoordinateX"):
                    parti = True
                if line.startswith(" _rln"):
                    output_file.write(line.strip()+" #%d \n"%i)
                    i = i+1
                    index = i
                else:
                    output_file.write(line)
        
        if parti == False:
             with open(self._getFileName('input_particles_m'), 'r') as input_file, open(self._getFileName('input_particles_m2'), 'w') as output_file:
                 j = 0 #mutex lock
                 i = 0 #start
                 #k = 1
                 for line in input_file:
                     if line.startswith("_rln"):
                         output_file.write(line)
                         i = 1
                     elif i == 0:
                         output_file.write(line)
                     elif j == 0:
                         # Create dummy coordinate for extraction only
                         output_file.write('_rlnCoordinateX #%d\n'%index)
                         output_file.write('_rlnCoordinateY #%d\n'%(index+1))
                         line = line.rstrip()
                         if len(line.split('@')) == 1:
                             lines = line.split('Runs')
                             line = lines[0]+'1@Runs'+lines[1]
                         output_file.write(line+' 0.5 0.5\n')
                         #k = k+1
                         j = 1
                     else:
                         line = line.rstrip()
                         if len(line.split('@')) == 1:
                             lines = line.split('Runs')
                             line = lines[0]+'1@Runs'+lines[1]
                         output_file.write(line+' 0.5 0.5\n')    
                         #k = k+1
        else:
            shutil.copyfile(self._getFileName('input_particles_m'),self._getFileName('input_particles_m2'))
        params = self._getFileName('input_particles_m2')
        params += ' '+ self._getPath()+'/Particles'
        params += ' --box_size=%d'%(self.boxsize.get())+' --create_stack'
                    
        if os.path.exists(self._getPath()+'/Particles'):
            shutil.rmtree(self._getPath()+'/Particles') #remove directory and its contents
        self.runJob("/home/user/EMAN2/bin/sxrelion2sphire.py", params, numberOfMpi=1) #cwd=self._getPath()) #do not use cwd here!!

    def processStep(self):
        # Enter here to generate the star file or to preprocess the images
        params = ' \'Particles/sphire_stack.hdf\' \'Class2D\' ' 
        params += ' --radius=%d'%(self.radius.get())
        params += ' --img_per_grp=%d'%(self.numberOfImages.get())
        params += ' --target_radius=%d'%(self.target_radius.get())
        params += ' --target_nx=%d'%(self.target_box_size.get())
        params += ' --restart=%d'%(self.restart.get())
        params += ' --thld_err=' + self.thld_err.get()
        if self.doCTF:
            params += ' --CTF'
        if self.doPhase:
            params += ' --VPP'

        self.runJob("/home/user/EMAN2/bin/sxisac2.py",
                    params, cwd=self._getPath())

    
    def createOutputStep(self):
        
        if self.doBeautify:
            params = self._getFileName('out_particles')+" "+self._getFileName('out_db')
            self.runJob("/home/user/EMAN2/bin/e2proc2d.py", params, numberOfMpi=1)
            
            params = "--adjust_to_analytic_model --stack="+ self._getFileName('out_db') + " --isac_dir=" + self._getFileName('isac_dir') + " --output_dir="+ self._getPath()+"/Class_Beau" + " --pixel_size="+self.pixelsize.get()+ " --radius="+str(self.radius.get())
            if self.doCTF == False:
                params += ' --noctf'
            self.runJob("/home/user/EMAN2/bin/sxcompute_isac_avg.py", params)


        if self.doBeautify:
            self.runJob("/home/user/scipion/software/em/sphire/save_class.py", self._getFileName('class_average_b')+" "+self._getFileName('out_particles')+" "+self._getFileName('notprocessfile')+" "+self._getFileName('params')+" "+self._getFileName('params2')+" "+self._getPath(), numberOfMpi=1)
            self._loadClassesInfo(self._getFileName("out_class"))
        else:
            self.runJob("/home/user/scipion/software/em/sphire/save_class.py", self._getFileName('class_average')+" "+self._getFileName('out_particles')+" "+self._getFileName('notprocessfile')+" "+self._getFileName('params')+" "+self._getFileName('params2')+" "+self._getPath(), numberOfMpi=1)
            self._loadClassesInfo(self._getFileName("out_class"))

        classes = np.load(self._getPath()+"/classes.npy")
        classes = classes.tolist()
        P = np.load(self._getPath()+"/params.npy")
        P = P.tolist()
        
        ids = []
        with open(self._getFileName("processfile"), 'r') as infile:
            for line in infile:
                ids.append(line.split()[0])
       
        with open(self._getFileName('input_particles_m2'), 'r') as input_file, open(self._getFileName('input_particles_m3'), 'w') as output_file:
            j = 0 #mutex lock
            i = 0 #start
            k = 0
            l = 0
            for line in input_file:
                if line.startswith("_rln"):
                    output_file.write(line)
                    i = 1
                elif i == 0:
                    output_file.write(line)
                elif j == 0:
                    output_file.write('_rlnClassNumber\n')
                    output_file.write('_rlnAnglePsi\n')
                    output_file.write('_rlnOriginX\n')
                    output_file.write('_rlnOriginY\n')
                    if str(k) in ids:
                        iid = self._find_in_list_of_list(classes, k)
                        output_file.write(line.rstrip()+' '+str(iid+1)+' '+str(P[l][0])+' '+str(P[l][1])+' '+str(P[l][2])+'\n')
                        l = l+1
                    else:
                        output_file.write(line.rstrip()+' '+str(len(classes)+1)+' 0 '+' 0 '+' 0 '+'\n')
                    j = 1
                else:
                    k = k +1
                    if str(k) in ids:
                        iid = self._find_in_list_of_list(classes, k)
                        output_file.write(line.rstrip()+' '+str(iid+1)+' '+str(P[l][0])+' '+str(P[l][1])+' '+str(P[l][2])+'\n')
                        l = l+1
                    else:
                        output_file.write(line.rstrip()+' '+str(len(classes)+1)+' 0 '+' 0 '+' 0 '+'\n')


        inputParticles = self.inputParticles.get()
        classes2DSet = self._createSetOfClasses2D(inputParticles)
        self._fillClassesFromLevel(classes2DSet)
  
        self._defineOutputs(outputClasses=classes2DSet)
        self._defineSourceRelation(self.inputParticles, classes2DSet)

    def _loadClassesInfo(self, filename):
        """ Read some information about the produced 2D classes
        from the metadata file.
        """
        self._classesInfo = {}  # store classes info, indexed by class id

        mdClasses = md.MetaData(filename)

        for classNumber, row in enumerate(md.iterRows(mdClasses)):
            index, fn = xmippToLocation(row.getValue(md.MDL_IMAGE))
            # Store info indexed by id, we need to store the row.clone() since
            # the same reference is used for iteration
            self._classesInfo[classNumber + 1] = (index, fn, row.clone())
        self._numClass = index
        print("number of class is "+str(index))

    def _find_in_list_of_list(self, mylist, char):
        for sub_list in mylist:
            if char in sub_list:
                return (mylist.index(sub_list))
        return -1

    def _fillClassesFromLevel(self, clsSet):
        """ Create the SetOfClasses2D from a given iteration. """
        xmpMd = self._getFileName("input_particles_m3") #the particle with orientation parameters (all_parameters)

        clsSet.classifyItems(updateItemCallback=self._updateParticle,
                                 updateClassCallback=self._updateClass,
                                 itemDataIterator=md.iterRows(xmpMd,
                                                          sortByLabel=md.MDL_ITEM_ID)) # relion style
    # --------------------------- INFO functions -------------------------------
    def _validate(self):
        """ Should be overriden in subclasses to 
        return summary message for NORMAL EXECUTION. 
        """
        validateMsgs = []
        return validateMsgs
    
    # --------------------------- UTILS functions ------------------------------
    def _updateParticle(self, item, row):
        item.setClassId(row.getValue(md.RLN_PARTICLE_CLASS))
        item.setTransform(rowToAlignment(row, em.ALIGN_2D)) # Not sure
        
        item._rlnAnglePsi = em.Float(row.getValue('rlnAnglePsi'))
        item._rlnOriginX = em.Float(row.getValue('rlnOriginX'))
        item._rlnOriginY = em.Float(row.getValue('rlnOriginY'))
        item._rlnClassNumber = em.String(row.getValue('rlnClassNumber'))
        
    def _updateClass(self, item):
        classId = item.getObjId()
        if classId in self._classesInfo:
            index, fn, row = self._classesInfo[classId]
            item.setAlignment2D()
            item.getRepresentative().setLocation(index, fn)     
```

the save_class.py is mainly used to add the additional class and record the 2D orientation parameters as follows:

```
#!/usr/bin/env python


from sparx import *
from sys import argv
import numpy as np

ref = EMData.read_images(argv[1])
images = EMData.read_images(argv[2])
ids = []
with open(argv[3], 'r') as infile:
    for line in infile:
        ids.append(line.split()[0])

classes =[]
for i in xrange(EMUtil.get_image_count(argv[1])):
    imagesc = get_im(argv[1],i)
    classes.append(imagesc.get_attr('members'))

np.save(argv[6]+"/classes.npy", classes)

ave = model_blank(images[0].get_xsize(),images[0].get_xsize())
for i in xrange(len(ids)):   
    Util.add_img(ave, images[i])
    Util.mul_scalar(ave, 1.0 /float(len(ids)) )

ave1  = resample(ave, float(ref[0].get_xsize())/images[0].get_xsize())
for i, img in enumerate(ref):
    img.write_image(argv[6]+"/output.hdf",i)
ave1.write_image(argv[6]+"/output.hdf",i+1)

params = read_text_row(argv[4])
params2 = read_text_row(argv[5])

P = []
ratios = float(ref[0].get_xsize())/images[0].get_xsize()
for i in xrange(len(params)):
    pi = combine_params2( params2[i][0], params2[i][1], params2[i][2], params2[i][3], \
           params[i][0], params[i][1]/ratios, params[i][2]/ratios, params[i][3])
    P.append(pi)

``` 

However, I  haven't deal with some problems 
1) I am not sure how to correctly save the 2D orientation parameters of ISAC2(Sphire) back into the transform matrix of scipion.
2) I need to remove the classid and alignment parameters when I call the writeSetOfParticles in the convertInputStep so that the output star file will contain the correct parameters(classnumber, 2D orientation parameters).

Any suggestions about the problem?

Thanks again for the help!

**Comment by pconesa** [comment]
Thanks @phonchi , for the 2D orientations take a look at what relion wrappers/plugin is doing:

https://github.com/I2PC/scipion/blob/master/pyworkflow/em/packages/relion/convert.py#L350

As for the second....point...I understand that you don't want any 2D alignment info as input, is that right?
There is an arg 'alignType' that may work if you use em.ALIGN_NONE:

`writeSetOfParticles(imgSet, self._getFileName('input_particles'), outputDir=self._getExtraPath(), fillMagnification=True, RemoveClassAngle=True, alignType=em.ALIGN_PROJ)`

Did you added the RemoveClassAngle?
The files you need to generate, are standard relion files?, if so we should be able to do it with existing relion code.

Could you explain a bit what are the tweaks you need to do for the ISAC2 input files and how are they different from relion ones?

**Comment by pconesa** [comment]
@delarosatrevin, @azazellochg , and @josuegbl are the maintainers of relion code....they are more familiar than me and might be able to give us some hint too about how far can we go using relion convert.py to get your files.

**Comment by delarosatrevin** [comment]
Hi @phonchi , as @pconesa said, thanks for contributing with this new protocol. 
I also think that will be better if you can create a fork or a separate branch, where we can check the code and also setup test that could be run automatically. This will help to check that the protocol is working as expected. 

I haven't look in the detail in the code, but still there are a couple things that I noticed:
* First, there are some hardcoded file path, I think this should be changed and make it relative where the sphire installation is.
* Second, why do you need here to convert first to .star files, as far as I know, ISAC/sphire use eman2 like file such as .hdf5. It seems like double unnecessary conversions.
