### ISSUE TITLE
xmipp3 - localdeblur sharpening fails....

### ISSUE THREAD

**Issue by josuegbl** [I2PC/scipion#1773]
**Describe the bug**
xmipp3 - localdeblur sharpening fails....
I used monores output as resolution map.

**To Reproduce**
1- execute localdeblur protocol
error:

00034:   ====================
00035:   Iteration  1
00036:   xmipp_volume_local_sharpening  -o Runs/001995_XmippProtLocSharp/extra/sharpenedMap_1.mrc  --resolution_map Runs/001941_XmippProtMonoRes/extra/mgresolution.vol --sampling 1.070000 -n 4 -k 0.025000 --md Runs/001995_XmippProtLocSharp/tmp/params.xmd --vol Runs/001821_ProtImportVolumes/extra/relion_class001.mrc:mrc
00037:   Starting...
00038:   used procesors = 4
00039:   maxRes = 28.5333  minRes = 2.78374
00040:     lambda  30.8818
00041:   xmipp_image_header -i Runs/001995_XmippProtLocSharp/extra/sharpenedMap_1.mrc -s 1.070000 
00042:   Setting sampling rate into headers...
00043:   Input: Runs/001995_XmippProtLocSharp/extra/sharpenedMap_1.mrc
00044:   New sampling rate (Angstrom) = 1.07
00045:   Traceback (most recent call last):
00046:     File "/home/josuegbl/SOFTWARE/scipion/pyworkflow/protocol/protocol.py", line 190, in run
00047:       self._run()
00048:     File "/home/josuegbl/SOFTWARE/scipion/pyworkflow/protocol/protocol.py", line 237, in _run
00049:       resultFiles = self._runFunc()
00050:     File "/home/josuegbl/SOFTWARE/scipion/pyworkflow/protocol/protocol.py", line 233, in _runFunc
00051:       return self._func(*self._args)
00052:     File "/home/josuegbl/SOFTWARE/scipion/pyworkflow/em/packages/xmipp3/protocol_volume_local_sharpening.py", line 251, in sharpeningAndMonoResStep
00053:       self.MonoResStep(iteration)
00054:     File "/home/josuegbl/SOFTWARE/scipion/pyworkflow/em/packages/xmipp3/protocol_volume_local_sharpening.py", line 182, in MonoResStep
00055:       params += ' --volumeRadius %f' % radius
00056:   TypeError: float argument required, not NoneType
00057:   Protocol failed: float argument required, not NoneType
00058:   FAILED: sharpeningAndMonoResStep, step 4
00059:     2018-09-18 14:33:26.320477
00060:   ------------------- PROTOCOL FAILED (DONE 4/5)

**Expected behavior**
A clear and concise description of what you expected to happen (that xmipp programs finish without errors :tongue: )

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Ubuntu 16.04]
 - Version release-1.2.1

**Comment by pconesa** [comment]
Thank you @josuegbl ...I take this is happening in release-1.2.1, right?

**Comment by josuegbl** [comment]
Yes @pconesa.
