### ISSUE TITLE
dependency step tree fails

### ISSUE THREAD

**Issue by josuegbl** [I2PC/scipion#1824]
**Describe the bug**
for certain protocols, when createOutputStep has been created before other steps (for example, streaming protocols), the tree step visualizacion fails.
**To Reproduce**
1- execute one protocol in streaming (not import protocol)

error: 
Traceback (most recent call last):
  File "/home/josuegbl/SOFTWARE/scipion-pluginization/software/lib/python2.7/lib-tk/Tkinter.py", line 1541, in __call__
    return self.func(*args)
  File "/home/josuegbl/SOFTWARE/scipion-pluginization/pyworkflow/gui/project/viewprotocols.py", line 303, in _showTree
    g = self._protocol.getStepsGraph()
  File "/home/josuegbl/SOFTWARE/scipion-pluginization/pyworkflow/protocol/protocol.py", line 1888, in getStepsGraph
    stepsDict[p].addChild(n)
KeyError: '8'

**Comment by pconesa** [comment]
Aha! I closed a similar one because it wasn't happening. Good catch!
