### ISSUE TITLE
If gctf fail, the whole protocol fails

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion#1854]
**Describe the bug**
For some reason, gctf has failed, not sure why. This was at eBic, and we might be able to find the mic that failed. Once this happens, gctf protocol, continues, tries to move the generated files, that do not exist , because the binary failed.

**To Reproduce**
1. I guess import 2 micrographs (mic1.mrc mic2.mrc, e.g.)
2. replace mic1.mrc with a txt file keeping the same name, this should cause gctf to fail.
3. Protocol fails, complaining about not able to move files. and mic2,.mrc is never processed

**Expected behavior**
A: it should keep processing
B: Probably, Base class, for all ctf, should take care of this case?

**Desktop (please complete the following information):**
 - Version: 1.1, master and pluginization should fail if I read the code right.

**Comment by joshua4289** [comment]
What exists : the micrograph input to Gctf in the tmp of Gctf protocol
                     the folder created from the micrograph name in extra 

What isn't created : The output of the estimation in extra/mic_name/ctfEstimation.txt
                                the psd which is an output of the same process
The protocol fails because it's trying to move the psd file which does not exist . 

I re-ran Gctf 1.06 on a "failed micrograph " and it ran successfully and created the psd file as it should

**Comment by joshua4289** [comment]
The trace back from the log file 

ERROR: Gctf has failed for micrograph Runs/000120_ProtGctf/tmp/GridSquare_14470925_Data_FoilHole_14476632_Data_14477770_14477771_20181216_1703-107691_aligned_mic.mrc
Traceback (most recent call last):
  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/pyworkflow/protocol/executor.py", line 144, in run
    self.step._run()  # not self.step.run() , to avoid race conditions
  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/pyworkflow/protocol/protocol.py", line 233, in _run
    resultFiles = self._runFunc()
  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/pyworkflow/protocol/protocol.py", line 229, in _runFunc
    return self._func(*self._args)
  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/pyworkflow/em/packages/gctf/protocol_gctf.py", line 287, in _estimateCTF
    pwutils.moveFile(micFnCtf, psdFile)
  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/pyworkflow/utils/path.py", line 227, in moveFile
    copyFile(source, dest)
  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/pyworkflow/utils/path.py", line 222, in copyFile
    shutil.copy(source, dest)
  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/software/lib/python2.7/shutil.py", line 119, in copy
    copyfile(src, dst)
  File "/dls_sw/apps/scipion/release-1.1-headless-devel/scipion/software/lib/python2.7/shutil.py", line 82, in copyfile
    with open(src, 'rb') as fsrc:
IOError: [Errno 2] No such file or directory: 'Runs/000120_ProtGctf/tmp/GridSquare_14470925_Data_FoilHole_14476632_Data_14477770_14477771_20181216_1703-107691_aligned_mic.ctf'

**Comment by pconesa** [comment]
@joshua4289 , you said that a "rerun" fo gctf with the same mic, worked...? Apart from solving this issue, that make me think if there is something else....the log you posted confirms that we should not do the "move"....but is there any hint about what happened to the first run of gctf? why it failed?
