### ISSUE TITLE
Exception if double click on Input or Output in summary tab

### ISSUE THREAD

**Issue by yaizar** [I2PC/scipion#1925]
I accidentally double clicked on the word "Output" instead of the actual output and it causes an exception in the console

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/yaiza/git/scipion/software/lib/python2.7/lib-tk/Tkinter.py", line 1541, in __call__
    return self.func(*args)
  File "/home/yaiza/git/scipion/pyworkflow/gui/tree.py", line 316, in _onDoubleClick
    actions = self.provider.getObjectActions(obj)
  File "/home/yaiza/git/scipion/pyworkflow/gui/project/viewprotocols.py", line 486, in getObjectActions
    viewers = em.findViewers(obj.getClassName(), DESKTOP_TKINTER)
  File "/home/yaiza/git/scipion/pyworkflow/em/__init__.py", line 99, in findViewers
    cls = findClass(className)
  File "/home/yaiza/git/scipion/pyworkflow/em/__init__.py", line 62, in findClass
    raise Exception("findClass: class '%s' not found." % className)
Exception: findClass: class 'String' not found.
```

**Comment by dmaluenda** [comment]
I'm getting no error but a label/comment edition dialog box is raised with empty field. However, if I type something in the fields, it have no effect. In fact, I don't know where it should go that label/comment...
