### ISSUE TITLE
Plugin manager is imported by default

### ISSUE THREAD

**Issue by delarosatrevin** [I2PC/scipion#1944]
**Describe the bug**
The plugin manager (plugin_funcs.py) are imported by default and an error is raised if the variable SCIPION_PLUGIN_REPO_URL is not defined.

```
(base) airen@airen-GL552JX:~/work/development/scipion-devel$ scipion &
[2] 2472
(base) airen@airen-GL552JX:~/work/development/scipion-devel$ 
Scipion v2.0 (2019-02-20) Diocletian (devel b5ae9a0)

>>>>> python  /home/airen/work/development/scipion-devel/pyworkflow/apps/pw_manager.py 
Traceback (most recent call last):
  File "/home/airen/work/development/scipion-devel/pyworkflow/apps/pw_manager.py", line 32, in <module>
    from pyworkflow.gui.project import ProjectManagerWindow
  File "/home/airen/work/development/scipion-devel/pyworkflow/gui/project/__init__.py", line 27, in <module>
    from project import ProjectManagerWindow, ProjectWindow
  File "/home/airen/work/development/scipion-devel/pyworkflow/gui/project/project.py", line 49, in <module>
    from pyworkflow.gui.plugin_manager import PluginManager
  File "/home/airen/work/development/scipion-devel/pyworkflow/gui/plugin_manager.py", line 35, in <module>
    from pyworkflow.install.plugin_funcs import PluginRepository, PluginInfo
  File "/home/airen/work/development/scipion-devel/pyworkflow/install/plugin_funcs.py", line 16, in <module>
    os.environ['SCIPION_PLUGIN_REPO_URL'])
  File "/home/airen/work/development/scipion-devel/software/lib/python2.7/UserDict.py", line 40, in __getitem__
    raise KeyError(key)
KeyError: 'SCIPION_PLUGIN_REPO_URL'
```

**Expected behavior**
* The install/plugin_funcs.py (and functionality there) should only be imported when requested.
* os.environ['SCIPION_PLUGIN_REPO_URL']) this should be centralized in the Config class in pyworkflow and have a reasonable default.

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu 16]

**Comment by fonsecareyna82** [comment]
The error was fixed!!!
I centralized the SCIPION_PLUGIN_REPO_URL varaible in the Config class in pyworkflow
