### ISSUE TITLE
broken viewer of interactive e2boxer

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#1953]
**Describe the bug**
I picked particles in EMAN2 GUI and saved output. After clicking Analyze results I get:

```
('writeCoordsConfig: state=', 'Manual')
Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/azazello/soft/scipion-devel/software/lib/python2.7/lib-tk/Tkinter.py", line 1541, in __call__
    return self.func(*args)
  File "/home/azazello/soft/scipion-devel/pyworkflow/gui/project/viewprotocols.py", line 1984, in _analyzeResultsClicked
    self._analyzeResults(prot)
  File "/home/azazello/soft/scipion-devel/pyworkflow/gui/project/viewprotocols.py", line 1964, in _analyzeResults
    firstViewer.visualize(prot)
  File "/home/azazello/soft/scipion-devel/pyworkflow/viewer.py", line 149, in visualize
    for view in self._visualize(obj, **kwargs):
TypeError: 'NoneType' object is not iterable
```

I am still trying to debug why this happens... There were some changes related to default viewers, can anyone comment on this?

**Desktop (please complete the following information):**
2.0.0-fixes

**Additional context**
Right clicking on the output and choosing DataViewer works!

**Comment by azazellochg** [comment]
must be related to https://github.com/I2PC/scipion/issues/1915 and https://github.com/I2PC/scipion/pull/1916

**Comment by pconesa** [comment]
fixed at eman repo

**Comment by azazellochg** [comment]
Thank you Pablo!

**Comment by pconesa** [comment]
;-)
https://github.com/scipion-em/scipion-em-eman2/pull/19
