### ISSUE TITLE
problem when installed scipion v2.0

### ISSUE THREAD

**Issue by liz18** [I2PC/scipion#2009]
The OS is Ubuntu 19.04
When installed SCIPION V2.0 by typing sudo ./scipoin install -j 5, the following appeared:

zhl@robot:/usr/local/scipion_v2.0$ sudo ./scipion install -j 5

Scipion v2.0 (2019-04-23) Diocletian

Building tcl ...
  All targets exist, skipping.
Done (0.00 seconds)
Building zlib ...
  All targets exist, skipping.
Done (0.00 seconds)
Building tk ...
  All targets exist, skipping.
Done (0.00 seconds)
Building png ...
  All targets exist, skipping.
Done (0.00 seconds)
Building jpeg ...
  All targets exist, skipping.
Done (0.00 seconds)
Building tiff ...
  All targets exist, skipping.
Done (0.00 seconds)
Building sqlite3 ...
  All targets exist, skipping.
Done (0.00 seconds)
Building hdf5 ...
  All targets exist, skipping.
Done (0.00 seconds)
Building python ...
  All targets exist, skipping.
Done (0.00 seconds)
Building pip ...
python pyworkflow/install/get-pip.py -I --no-setuptools
ERROR:root:code for hash md5 was not found.
Traceback (most recent call last):
  File "/usr/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type md5
ERROR:root:code for hash sha1 was not found.
Traceback (most recent call last):
  File "/usr/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha1
ERROR:root:code for hash sha224 was not found.
Traceback (most recent call last):
  File "/usr/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha224
ERROR:root:code for hash sha256 was not found.
Traceback (most recent call last):
  File "/usr/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha256
ERROR:root:code for hash sha384 was not found.
Traceback (most recent call last):
  File "/usr/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha384
ERROR:root:code for hash sha512 was not found.
Traceback (most recent call last):
  File "/usr/lib/python2.7/hashlib.py", line 147, in <module>
    globals()[__func_name] = __get_hash(__func_name)
  File "/usr/lib/python2.7/hashlib.py", line 97, in __get_builtin_constructor
    raise ValueError('unsupported hash type ' + name)
ValueError: unsupported hash type sha512
Traceback (most recent call last):
  File "pyworkflow/install/get-pip.py", line 19177, in <module>
    main()
  File "pyworkflow/install/get-pip.py", line 194, in main
    bootstrap(tmpdir=tmpdir)
  File "pyworkflow/install/get-pip.py", line 82, in bootstrap
    import pip
  File "/tmp/tmpRRFHHK/pip.zip/pip/__init__.py", line 16, in <module>
    # * GNU General Public License for more details.
  File "/tmp/tmpRRFHHK/pip.zip/pip/vcs/mercurial.py", line 9, in <module>
  File "/tmp/tmpRRFHHK/pip.zip/pip/download.py", line 39, in <module>
  File "/tmp/tmpRRFHHK/pip.zip/pip/_vendor/requests/__init__.py", line 61, in <module>
    
  File "/tmp/tmpRRFHHK/pip.zip/pip/_vendor/requests/packages/__init__.py", line 29, in <module>
    
  File "/usr/lib/python2.7/site-packages/urllib3/__init__.py", line 8, in <module>
    from .connectionpool import (
  File "/usr/lib/python2.7/site-packages/urllib3/connectionpool.py", line 29, in <module>
    from .connection import (
  File "/usr/lib/python2.7/site-packages/urllib3/connection.py", line 39, in <module>
    from .util.ssl_ import (
  File "/usr/lib/python2.7/site-packages/urllib3/util/__init__.py", line 6, in <module>
    from .ssl_ import (
  File "/usr/lib/python2.7/site-packages/urllib3/util/ssl_.py", line 7, in <module>
    from hashlib import md5, sha1, sha256
ImportError: cannot import name md5
Error: target '/usr/local/scipion_v2.0/software/lib/python2.7/site-packages/pip' not built (after running 'python pyworkflow/install/get-pip.py -I --no-setuptools')

What could be the problem? How do I resolve it? Thanks!

**Comment by delarosatrevin** [comment]
Hi Liz,

I think that I had a similar issue before. Can you try to install
libopenssl (and libopenssl-dev, just in case) ??
I'm not completely sure, but I think that solves the problem.

Best,
Jose Miguel

**Comment by azazellochg** [comment]
I think I fixed this once by updating python to the latest 2.7.x

**Comment by liz18** [comment]
@delarosatrevin Thanks. I've tried but still failed.

**Comment by liz18** [comment]
@azazellochg How do I update the python version of scipion? I've updated the python version of Ubuntu to 3.7, but it doesn't related to the scipion's.

**Comment by pconesa** [comment]
To reinstall scipion python:

scipion python pyworkflow/install/clean.py python

that will reinstall python, therefore you will need to reinstall the plugins, but not the binaries behind (relion, eman, chimera,....should remain)

**Comment by pconesa** [comment]
review the log or paste it here to see if python is being compiled without ssh support.

**Comment by azazellochg** [comment]
Interesting because my issue was fixed by installing 2.7.13: https://github.com/I2PC/scipion/issues/783 Bit scipion 2.0 comes with 2.7.15 now

**Comment by pconesa** [comment]
interesting indeed! it depends what is the actual reason why @liz18 installation does not work.

**Comment by liz18** [comment]
Thanks all colleagues! It now works.

**Comment by azazellochg** [comment]
@liz18 reinstalling python helped?

**Comment by delarosatrevin** [comment]
Yes, @liz18 would be good to know the solution for the record.

**Comment by liz18** [comment]
@azazellochg Yes, I re-installed python.
