### ISSUE TITLE
tutorial: scipion_intro

### ISSUE THREAD

**Issue by rmarabini** [I2PC/scipion#257]
Eman picking ails with error (eman has being instaled at software/em/eman2.11.linux64/ )

sxprocess.py demoparms --makedb=thr_low=1.0:thr_hi=30.0:boxsize=110:gauss_width=1.0:pixel_input=1:pixel_output=1:invert_contrast=True:use_variance=True
00067:   /bin/sh: /home/roberto/DELETEME/scipion/software/em/eman2.11/bin/sxprocess.py: /home/xmipp/CNB/scipion/software/em/eman2.11.linux64/extlib/bin/python: bad interpreter: No such file or directory
00068:   Traceback (most recent call last):
00069:     File "/home/roberto/DELETEME/scipion/pyworkflow/protocol/protocol.py", line 167, in run
00070:       self._run()
00071:     File "/home/roberto/DELETEME/scipion/pyworkflow/protocol/protocol.py", line 930, in _run
00072:       self._insertAllSteps() # Define steps for execute later
00073:     File "/home/roberto/DELETEME/scipion/pyworkflow/em/packages/eman2/protocol_autopick.py", line 72, in _insertAllSteps
00074:       self.runJob('sxprocess.py', params, cwd=self.getWorkingDir())
00075:     File "/home/roberto/DELETEME/scipion/pyworkflow/protocol/protocol.py", line 960, in runJob
00076:       self._stepsExecutor.runJob(self._log, program, arguments, **kwargs)
00077:     File "/home/roberto/DELETEME/scipion/pyworkflow/protocol/executor.py", line 56, in runJob
00078:       env=env, cwd=cwd)
00079:     File "/home/roberto/DELETEME/scipion/pyworkflow/utils/process.py", line 51, in runJob
00080:       return runCommand(command, env, cwd)
00081:     File "/home/roberto/DELETEME/scipion/pyworkflow/utils/process.py", line 65, in runCommand
00082:       check_call(command, shell=True, stdout=sys.stdout, stderr=sys.stderr, env=env, cwd=cwd)
00083:     File "/home/roberto/DELETEME/scipion/software/lib/python2.7/subprocess.py", line 540, in check_call
00084:       raise CalledProcessError(retcode, cmd)
00085:   CalledProcessError: Command 'sxprocess.py demoparms --makedb=thr_low=1.0:thr_hi=30.0:boxsize=110:gauss_width=1.0:pixel_input=1:pixel_output=1:invert_contrast=True:use_variance=True' returned non-zero exit status 126
00086:   Cleaning temporarly files....
00087:   ------------------- PROTOCOL FAILED (DONE 0/0)

**Comment by rmarabini** [comment]
Sorry, sparx is the protocol that fails not eman. 

Is sparx instalated with eman?
Document does not comment on sparx but workflow includes it

**Comment by rmarabini** [comment]
By the way I did particle picking with eman and the process that not end. What

**Comment by rmarabini** [comment]
finally boxer finish but took a long time !?
