### ISSUE TITLE
building script fails

### ISSUE THREAD

**Issue by cbernau** [I2PC/scipion#328]
Dear scipion developers,

I could not find any contact Information on your website, so I'm posting this issue here.
Apologies in advance if this is the wrong place to do this.

I'm trying to install scipion on our Systems and unfortunately I cannot use your precompiled verisons I Need to build it using your building script.

However, I cannot get rid of the following error, that occurs when your building script tries to install matplotlib:

building 'matplotlib.ft2font' extension
Traceback (most recent call last):
  File "setup.py", line 268, in <module>
    **extra_args
  File "/home/hpc/pr28fa/ri72fuv2/SCIPION/src/scipion/software/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/home/hpc/pr28fa/ri72fuv2/SCIPION/src/scipion/software/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/home/hpc/pr28fa/ri72fuv2/SCIPION/src/scipion/software/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "build/bdist.linux-x86_64/egg/setuptools/command/install.py", line 67, in run
  File "build/bdist.linux-x86_64/egg/setuptools/command/install.py", line 109, in do_egg_install
  File "/home/hpc/pr28fa/ri72fuv2/SCIPION/src/scipion/software/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/home/hpc/pr28fa/ri72fuv2/SCIPION/src/scipion/software/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "build/bdist.linux-x86_64/egg/setuptools/command/bdist_egg.py", line 161, in run
  File "build/bdist.linux-x86_64/egg/setuptools/command/bdist_egg.py", line 147, in call_command
  File "/home/hpc/pr28fa/ri72fuv2/SCIPION/src/scipion/software/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/home/hpc/pr28fa/ri72fuv2/SCIPION/src/scipion/software/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "build/bdist.linux-x86_64/egg/setuptools/command/install_lib.py", line 9, in run
  File "/home/hpc/pr28fa/ri72fuv2/SCIPION/src/scipion/software/lib/python2.7/distutils/command/install_lib.py", line 111, in build
    self.run_command('build_ext')
  File "/home/hpc/pr28fa/ri72fuv2/SCIPION/src/scipion/software/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/home/hpc/pr28fa/ri72fuv2/SCIPION/src/scipion/software/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "build/bdist.linux-x86_64/egg/setuptools/command/build_ext.py", line 54, in run
  File "/home/hpc/pr28fa/ri72fuv2/SCIPION/src/scipion/software/lib/python2.7/distutils/command/build_ext.py", line 337, in run
    self.build_extensions()
  File "/home/hpc/pr28fa/ri72fuv2/SCIPION/src/scipion/software/lib/python2.7/distutils/command/build_ext.py", line 446, in build_extensions
    self.build_extension(ext)
  File "build/bdist.linux-x86_64/egg/setuptools/command/build_ext.py", line 187, in build_extension
  File "/home/hpc/pr28fa/ri72fuv2/SCIPION/src/scipion/software/lib/python2.7/distutils/command/build_ext.py", line 493, in build_extension
    include_dirs=ext.include_dirs,
  File "/home/hpc/pr28fa/ri72fuv2/SCIPION/src/scipion/software/tmp/matplotlib-1.3.1/setupext.py", line 699, in __get__
    result = obj._hooks[self._name]() + result
  File "/home/hpc/pr28fa/ri72fuv2/SCIPION/src/scipion/software/tmp/matplotlib-1.3.1/setupext.py", line 725, in include_dirs_hook
    import numpy
  File "/home/hpc/pr28fa/ri72fuv2/SCIPION/src/scipion/software/lib/python2.7/site-packages/numpy/__init__.py", line 153, in <module>
    from . import add_newdocs
  File "/home/hpc/pr28fa/ri72fuv2/SCIPION/src/scipion/software/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/home/hpc/pr28fa/ri72fuv2/SCIPION/src/scipion/software/lib/python2.7/site-packages/numpy/lib/__init__.py", line 17, in <module>
    from . import scimath as emath
ImportError: cannot import name scimath

To me it looks like a circular Import. If I simply start the python, that has been build during the previous part of the building process, and run 'from numpy.lib import scimath as emath' it will work without any problems.

Do you have some Workaround for this problem? Actually, I do not understand how this scipt can work on anyone's system. All the parts that are used in this script seem to pe part of the scipion build itself.

Best,
Christoph Bernau

**Comment by azazellochg** [comment]
Hello Christoph, 

I believe I had once a similar problem. Check, if installed numpy (1.8.1) was correctly detected during matplotlib configure (see the top of software/log/matplotlib.log file, that should contain _numpy: yes_). If this is not the case, try to replace the LD_LIBRARY_PATH in the long command for building matplotlib, displayed in the output of install script with this: LD_LIBRARY_PATH="/home/hpc/pr28fa/ri72fuv2/SCIPION/src/scipion/software/lib:$LD_LIBRARY_PATH". Then numpy should be detected and matplotlib will build successfully.
PS. I had to do the same during scipy building in the following steps.

**Comment by delarosatrevin** [comment]
Hi @cbernau , this way is perfectly fine to report bugs or suggest features. Maybe we should also add the contact information in the main page, even before entering in the wiki.

Try the suggestion of @azazellochg and let us know if work for you or not.

**Comment by cbernau** [comment]
Hi @azazellochg ,
yes, thanks, that did the job.

Best,
Christoph

**Comment by delarosatrevin** [comment]
Great! I will close this issue and check later if we can pass that variables in a better way from the install script.

**Comment by delarosatrevin** [comment]
@cbernau , just for completion, could you provide more details about your system (OS, version, libraries) to have more information to improve the installation system?

**Comment by cbernau** [comment]
well, the OS Version was SLES 11 SP3, not sure what libraries I should mention here because you provide them all bundled with scipion, don't you? Which libraries would you like to know?

**Comment by delarosatrevin** [comment]
Christop, thanks for the information. Do you know the versions of gcc, gfortran, openmpi?

**Comment by cbernau** [comment]
well, the gcc Version was 4.9
As far as mpi is concerned, we actually do not have openmpi here but we use Intel-mpi (Version 5.1).
After some small modifications the building of scipion seemed to work (i.e. scipion reported that the building process was succesful), but I still have to check whether the mpi-versions of the programs really work. Do you have any experience with running scipion with Intel-mpi?

**Comment by delarosatrevin** [comment]
Thanks. The most used mpi library is OpenMpi, but I know at least one that have compiled successfully with Intel-MPI.
