### ISSUE TITLE
cannot configure scipion with openmpi installed in custom paths ?

### ISSUE THREAD

**Issue by pescobar** [I2PC/scipion#357]
Hi,

I am trying to install scipion in my cluster and I found some issues when trying to use my openmpi installation in a custom path. 

Before the installation I have defined `MPI_INCLUDE` and `MPI_LIBDIR`

```
[escobar@login11 ]$ env |egrep ^MPI
MPI_INCLUDE=/scicore/soft/apps/OpenMPI/1.6.4-GCC-4.7.2/include
MPI_LIBDIR=/scicore/soft/apps/OpenMPI/1.6.4-GCC-4.7.2/lib
```

Variables `LD_LIBRARY_PATH`, `PATH`, `CPATH` are also correctly defined when loading the openmpi module but still when I run `./scipion config` I get this error:

```
Checking paths in /scicore/home/scicore/escobar/soft-compilation/test-scipion/src/scipion/config/scipion.conf ...
  Path to MPI_LIBDIR (/usr/lib64/mpi/gcc/openmpi/lib) should exist but it doesn't.
  Path to MPI_INCLUDE (/usr/lib64/mpi/gcc/openmpi/include) should exist but it doesn't.
  Cannot find file: /usr/lib64/mpi/gcc/openmpi/include/mpi.h
Errors found.
```

Is there any way to force scipion to use the openmpi libraries in my custom paths? I have checked that if I hardcode the paths in scipion.conf it works but I would like to avoid hardcoding paths so if I want to use a different openmpi version the installation procedure keeps the same and I it's easier to automatize. Is this possible?

thanks in advance for your help.

**Comment by delarosatrevin** [comment]
Hi,  
Currently the only way is to change the scipion.conf and the MPI variables there.
Anyway I agree with you that having a way to pass those values during the installation, the process could be easily automatized.
Something like:
./scipion config MPI_LIBDIR=/path/mpi/lib
I will this as a feature for a future version. Thanks for the suggestion.

Anyway, if you are installing in a cluster I would suggest to better install from source than from binary.

**Comment by pescobar** [comment]
Hola Jose Miguel,

thanks for taking into account my suggestion. By now I will patch the file `config/templates/scipion.template` with my custom paths for my automated installation

I tried to compile from sources but I had some issues. The first issue was when compiling lapack I was getting this error in the cmake log file:

```
Detecting Fortran/C Interface - Failed to compile
```

I solved this by doing `export FC=gfortran` before compiling but then I have hit this other issue when compiliing matplotlib

```
building 'matplotlib.ft2font' extension
Traceback (most recent call last):
  File "setup.py", line 268, in <module>
    **extra_args
  File "/scicore/home/scicore/escobar/soft-compilation/scipion-source/scipion/software/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/scicore/home/scicore/escobar/soft-compilation/scipion-source/scipion/software/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/scicore/home/scicore/escobar/soft-compilation/scipion-source/scipion/software/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "build/bdist.linux-x86_64/egg/setuptools/command/install.py", line 67, in run
  File "build/bdist.linux-x86_64/egg/setuptools/command/install.py", line 109, in do_egg_install
  File "/scicore/home/scicore/escobar/soft-compilation/scipion-source/scipion/software/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/scicore/home/scicore/escobar/soft-compilation/scipion-source/scipion/software/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "build/bdist.linux-x86_64/egg/setuptools/command/bdist_egg.py", line 161, in run
  File "build/bdist.linux-x86_64/egg/setuptools/command/bdist_egg.py", line 147, in call_command
  File "/scicore/home/scicore/escobar/soft-compilation/scipion-source/scipion/software/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/scicore/home/scicore/escobar/soft-compilation/scipion-source/scipion/software/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "build/bdist.linux-x86_64/egg/setuptools/command/install_lib.py", line 9, in run
  File "/scicore/home/scicore/escobar/soft-compilation/scipion-source/scipion/software/lib/python2.7/distutils/command/install_lib.py", line 111, in build
    self.run_command('build_ext')
  File "/scicore/home/scicore/escobar/soft-compilation/scipion-source/scipion/software/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/scicore/home/scicore/escobar/soft-compilation/scipion-source/scipion/software/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "build/bdist.linux-x86_64/egg/setuptools/command/build_ext.py", line 54, in run
  File "/scicore/home/scicore/escobar/soft-compilation/scipion-source/scipion/software/lib/python2.7/distutils/command/build_ext.py", line 337, in run
    self.build_extensions()
  File "/scicore/home/scicore/escobar/soft-compilation/scipion-source/scipion/software/lib/python2.7/distutils/command/build_ext.py", line 446, in build_extensions
    self.build_extension(ext)
  File "build/bdist.linux-x86_64/egg/setuptools/command/build_ext.py", line 187, in build_extension
  File "/scicore/home/scicore/escobar/soft-compilation/scipion-source/scipion/software/lib/python2.7/distutils/command/build_ext.py", line 493, in build_extension
    include_dirs=ext.include_dirs,
  File "/scicore/home/scicore/escobar/soft-compilation/scipion-source/scipion/software/tmp/matplotlib-1.3.1/setupext.py", line 699, in __get__
    result = obj._hooks[self._name]() + result
  File "/scicore/home/scicore/escobar/soft-compilation/scipion-source/scipion/software/tmp/matplotlib-1.3.1/setupext.py", line 725, in include_dirs_hook
    import numpy
  File "/scicore/home/scicore/escobar/soft-compilation/scipion-source/scipion/software/lib/python2.7/site-packages/numpy/__init__.py", line 153, in <module>
    from . import add_newdocs
  File "/scicore/home/scicore/escobar/soft-compilation/scipion-source/scipion/software/lib/python2.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/scicore/home/scicore/escobar/soft-compilation/scipion-source/scipion/software/lib/python2.7/site-packages/numpy/lib/__init__.py", line 17, in <module>
    from . import scimath as emath
ImportError: cannot import name scimath
```

As I have no time to debug this problem now because my users need scipion installed urgently I decided to try the binary distribution.

**Comment by delarosatrevin** [comment]
Hola Pablo, 

Thanks for the feedback. I think it is a good solution to customize the .template for your needs. 
Have you installed the pre-requisites for Centos? I'm not sure if we have tested in 6.5 version.
@tranquilinho , Have you seen the following error?
building 'matplotlib.ft2font' extension
I remember something about it, but not sure.

Pablo, did the binary run properly? Let us know if you have any problem and we can help.

**Comment by azazellochg** [comment]
@pescobar ,
the solution for the error with scimath can be found here: #328

**Comment by pescobar** [comment]
HI @azazellochg . thanks for the tip but this didn't solved my problem. I have setup these env vars:

```
[escobar@login11 log]$ echo $LD_LIBRARY_PATH 
/scicore/home/scicore/escobar/soft-compilation/scipion-source/scipion/software/lib:/scicore/home/scicore/escobar/soft-compilation/scipion-source/scipion/software/lib/:/scicore/soft/apps/GSL/1.16-goolf-1.4.10/lib:/scicore/soft/apps/ScaLAPACK/2.0.2-gompi-1.4.10-OpenBLAS-0.2.6-LAPACK-3.4.2/lib:/scicore/soft/apps/FFTW/3.3.3-gompi-1.4.10/lib:/scicore/soft/apps/OpenBLAS/0.2.6-gompi-1.4.10-LAPACK-3.4.2/lib:/scicore/soft/apps/OpenMPI/1.6.4-GCC-4.7.2/lib:/scicore/soft/apps/hwloc/1.6.2-GCC-4.7.2/lib:/scicore/soft/apps/GCC/4.7.2/lib/gcc/x86_64-unknown-linux-gnu/4.7.2:/scicore/soft/apps/GCC/4.7.2/lib64:/scicore/soft/apps/GCC/4.7.2/lib
```

```
[escobar@login11 log]$ echo $PYTHONPATH
/scicore/home/scicore/escobar/soft-compilation/scipion-source/scipion/software/lib/python2.7/site-packages/numpy/lib:scicore/home/scicore/escobar/soft-compilation/scipion-source/scipion/software/lib/python2.7/site-packages:/scicore/home/scicore/escobar/soft-compilation/scipion-source/scipion/software/lib/python2.7
```

I have also checked in the numpy build log that scimath seems to be built

```
[escobar@login11 log]$ grep -Ri scimath numpy.log 
copying numpy/lib/scimath.py -> build/lib.linux-x86_64-2.7/numpy/lib
copying build/lib.linux-x86_64-2.7/numpy/lib/scimath.py -> /scicore/home/scicore/escobar/soft-compilation/scipion-source/scipion/software/lib/python2.7/site-packages/numpy/lib
byte-compiling /scicore/home/scicore/escobar/soft-compilation/scipion-source/scipion/software/lib/python2.7/site-packages/numpy/lib/scimath.py to scimath.pyc
```

but still I get the same error about `ImportError: cannot import name scimath` when building matplotlib. By now I think I will use the binary release. I will provide some feedback when my users test it

**Comment by azazellochg** [comment]
Hi @pescobar , that's strange. For me the problem was not related to numpy or scimath at all, but rather matplotlib that could not detect the installed numpy.

**Comment by pescobar** [comment]
yes I agree, it seems like it cannot fine the numpy installation. That's why I tried to define PYTHONPATH like this:

```
echo [escobar@login11 scipion]$ echo $PYTHONPATH 
/scicore/home/scicore/escobar/soft-compilation/scipion-source/scipion/software/lib/python2.7/site-packages

[escobar@login11 scipion]$ ls $PYTHONPATH
easy-install.pth  numpy-1.8.1-py2.7.egg-info      pyparsing.py   python_dateutil-1.5-py2.7.egg  setuptools-5.4.1-py2.7.egg  site.py   six-1.7.3-py2.7.egg
numpy             pyparsing-2.0.2-py2.7.egg-info  pyparsing.pyc  README                         setuptools.pth              site.pyc
```

but anyway I still get the same error....

**Comment by azazellochg** [comment]
@pescobar I see. Probably you misunderstood my solution in the referenced issue. You dont have to change the bar themselves but replace the part of the line Scipion uses to compile matplotlib. For example you have "g++ blablabla LD_LIBRARY_PATH=some text blablabla" in std output when Scipion installer is running after configure of the matplotlib. Here it will fail and you have rerun this long compile command again yourself,  substituting the ld library var as I mentioned in the other issue. Next you rerun Scipion installer and it will skip building matplotlib since it would be installed.

**Comment by pescobar** [comment]
thanks for you help @azazellochg  but here you can see my full stdout error and you can see there that LD_LIBRARY_PATH is defined pointing to /path/to/scipion/software/lib but still I get the same error. Maybe I am missing dome dependencies.

```
CPPFLAGS="-I/scicore/home/scicore/escobar/soft-compilation/scipion-source/scipion/software/include -I/scicore/home/scicore/escobar/soft-compilation/scipion-source/scipion/software/lib/python2.7/site-packages/numpy/core/include -I/scicore/home/scicore/escobar/soft-compilation/scipion-source/scipion/software/lib/python2.7/site-packages/numpy/core/include/numpy" PATH="/scicore/home/scicore/escobar/soft-compilation/scipion-source/scipion/software/bin:/scicore/home/scicore/escobar/soft-compilation/scipion-source/scipion/software/bin:/scicore/soft/apps/Java/1.7.0_21/bin:/scicore/soft/apps/OpenMPI/1.6.4-GCC-4.7.2/bin:/scicore/soft/apps/GSL/1.16-goolf-1.4.10/bin:/scicore/soft/apps/CMake/2.8.12-goolf-1.4.10/bin:/scicore/soft/apps/FFTW/3.3.3-gompi-1.4.10/bin:/scicore/soft/apps/OpenMPI/1.6.4-GCC-4.7.2/bin:/scicore/soft/apps/hwloc/1.6.2-GCC-4.7.2/bin:/scicore/soft/apps/GCC/4.7.2/bin:/scicore/soft/UGE/current/bin/lx-amd64:/usr/lib64/qt-3.3/bin:/export/soft/lua_lmod/centos6/lmod/lmod/libexec:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/ibutils/bin:/scicore/home/scicore/escobar/bin" PYTHONHOME="/scicore/home/scicore/escobar/soft-compilation/scipion-source/scipion/software" LDFLAGS="-L/scicore/home/scicore/escobar/soft-compilation/scipion-source/scipion/software/lib " LD_LIBRARY_PATH="/scicore/home/scicore/escobar/soft-compilation/scipion-source/scipion/software/lib" /scicore/home/scicore/escobar/soft-compilation/scipion-source/scipion/software/bin/python setup.py install --prefix=/scicore/home/scicore/escobar/soft-compilation/scipion-source/scipion/software > /scicore/home/scicore/escobar/soft-compilation/scipion-source/scipion/software/log/matplotlib.log 2>&1


Error: target 'software/lib/python2.7/site-packages/matplotlib-1.3.1*' not built (after running 'CPPFLAGS="-I/scicore/home/scicore/escobar/soft-compilation/scipion-source/scipion/software/include -I/scicore/home/scicore/escobar/soft-compilation/scipion-source/scipion/software/lib/python2.7/site-packages/numpy/core/include -I/scicore/home/scicore/escobar/soft-compilation/scipion-source/scipion/software/lib/python2.7/site-packages/numpy/core/include/numpy" PATH="/scicore/home/scicore/escobar/soft-compilation/scipion-source/scipion/software/bin:/scicore/home/scicore/escobar/soft-compilation/scipion-source/scipion/software/bin:/scicore/soft/apps/Java/1.7.0_21/bin:/scicore/soft/apps/OpenMPI/1.6.4-GCC-4.7.2/bin:/scicore/soft/apps/GSL/1.16-goolf-1.4.10/bin:/scicore/soft/apps/CMake/2.8.12-goolf-1.4.10/bin:/scicore/soft/apps/FFTW/3.3.3-gompi-1.4.10/bin:/scicore/soft/apps/OpenMPI/1.6.4-GCC-4.7.2/bin:/scicore/soft/apps/hwloc/1.6.2-GCC-4.7.2/bin:/scicore/soft/apps/GCC/4.7.2/bin:/scicore/soft/UGE/current/bin/lx-amd64:/usr/lib64/qt-3.3/bin:/export/soft/lua_lmod/centos6/lmod/lmod/libexec:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/ibutils/bin:/scicore/home/scicore/escobar/bin" PYTHONHOME="/scicore/home/scicore/escobar/soft-compilation/scipion-source/scipion/software" LDFLAGS="-L/scicore/home/scicore/escobar/soft-compilation/scipion-source/scipion/software/lib " LD_LIBRARY_PATH="/scicore/home/scicore/escobar/soft-compilation/scipion-source/scipion/software/lib" /scicore/home/scicore/escobar/soft-compilation/scipion-source/scipion/software/bin/python setup.py install --prefix=/scicore/home/scicore/escobar/soft-compilation/scipion-source/scipion/software > /scicore/home/scicore/escobar/soft-compilation/scipion-source/scipion/software/log/matplotlib.log 2>&1')
```

**Comment by delarosatrevin** [comment]
@pescobar , can you send me the scipion/software/log/matplotlib.log ?? To take a look and check if we can figure out the problem?

**Comment by pescobar** [comment]
matplotlib log
https://gist.github.com/e74e496b965251933acc

numpy log
https://gist.github.com/40a02c97e78052e117ae

thanks for taking a look at this

**Comment by azazellochg** [comment]
@pescobar, try to run in command line this:

CPPFLAGS="-I/scicore/home/scicore/escobar/soft-compilation/scipion-source/scipion/software/include -I/scicore/home/scicore/escobar/soft-compilation/scipion-source/scipion/software/lib/python2.7/site-packages/numpy/core/include -I/scicore/home/scicore/escobar/soft-compilation/scipion-source/scipion/software/lib/python2.7/site-packages/numpy/core/include/numpy" PATH="/scicore/home/scicore/escobar/soft-compilation/scipion-source/scipion/software/bin:/scicore/home/scicore/escobar/soft-compilation/scipion-source/scipion/software/bin:/scicore/soft/apps/Java/1.7.0_21/bin:/scicore/soft/apps/OpenMPI/1.6.4-GCC-4.7.2/bin:/scicore/soft/apps/GSL/1.16-goolf-1.4.10/bin:/scicore/soft/apps/CMake/2.8.12-goolf-1.4.10/bin:/scicore/soft/apps/FFTW/3.3.3-gompi-1.4.10/bin:/scicore/soft/apps/OpenMPI/1.6.4-GCC-4.7.2/bin:/scicore/soft/apps/hwloc/1.6.2-GCC-4.7.2/bin:/scicore/soft/apps/GCC/4.7.2/bin:/scicore/soft/UGE /current/bin/lx-amd64:/usr/lib64/qt-3.3/bin:/export/soft/lua_lmod/centos6/lmod/lmod/libexec:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/sbin:/opt/ibutils/bin:/scicore/home/scicore/escobar/bin" PYTHONHOME="/scicore/home/scicore/escobar/soft-compilation/scipion-source/scipion/software" LDFLAGS="-L/scicore/home/scicore/escobar/soft-compilation/scipion-source/scipion/software/lib " LD_LIBRARY_PATH="/scicore/home/scicore/escobar/soft-compilation/scipion-source/scipion/software/lib:$LD_LIBRARY_PATH" /scicore/home/scicore/escobar/soft-compilation/scipion-source/scipion/software/bin/python setup.py install --prefix=/scicore/home/scicore/escobar/soft-compilation/scipion-source/scipion/software > /scicore/home/scicore/escobar/soft-compilation/scipion-source/scipion/software/log/matplotlib.log 2>&1

If this fails, then it is probably something else..

**Comment by pescobar** [comment]
thanks for the tip @azazellochg  :) It seems scipion was overwriting my LD_LIBRARY_PATH and this was causing the trouble. I have sent you a pull request with the fix I did

https://github.com/I2PC/scipion/pull/363

**Comment by azazellochg** [comment]
@pconesa great! I'm glad it helped. I guess, @delarosatrevin could test if this change does not break compilation of other packages during scipion installation.

**Comment by delarosatrevin** [comment]
@azazellochg , I think you were referring to @pescobar. (Both are Pablo's)
@pescobar , Thanks for pointing the place where we are overwriting the LD_LIBRARY_PATH and @azazellochg  for the tips to workaround. I have commented inline a minor change in the Pull Request, but we need to test in other systems that this change does not affect other Python modules.

**Comment by delarosatrevin** [comment]
@pescobar , Should we close this issue? Since I it is fixed in #364 ?

**Comment by pescobar** [comment]
I opened this issue to ask if paths to mpi libs can be passed as arguments or env vars during the installation. You clarified that this is  not possible so I think it's fine to close it.

**Comment by delarosatrevin** [comment]
OK, I was confused. I will keep it open, but I have modified the label and marked as 'wish-list feature'.
