### ISSUE TITLE
ShowJ: out of memory when playing with the zoom.

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion#442]
In mi laptop, when ShowJ is loaded (with 30.000 thousands particles) and playing "agily" with the zoom out (shift mouse wheel), I'm getting an out of memory error:

"java.sql.SQLException: [SQLITE_CANTOPEN]  Unable to open the database file (out of memory)
"

**Comment by pconesa** [comment]
It might be related:

java.lang.Exception: XMIPP_ERROR 18: File cannot be open.
   Image Class::mmapFile: Error opening the image file to be mapped.
   File: software/em/xmipp/libraries/data/xmipp_image.h line: 1396

	at xmipp.jni.ImageGeneric.read(Native Method)
	at xmipp.jni.ImageGeneric.read(ImageGeneric.java:146)
	at xmipp.jni.ImageGeneric.read(ImageGeneric.java:142)
	at xmipp.ij.commons.XmippImageConverter.readToImagePlus(XmippImageConverter.java:137)
	at xmipp.ij.commons.XmippImageConverter.readToImagePlus(XmippImageConverter.java:110)
	at xmipp.ij.commons.XmippImageConverter.readToImagePlus(XmippImageConverter.java:89)
	at xmipp.ij.commons.XmippImageConverter.readToImagePlus(XmippImageConverter.java:84)
	at xmipp.ij.commons.ImagePlusFromFile.loadImagePlus(ImagePlusFromFile.java:63)
	at xmipp.ij.commons.ImagePlusReader.getImagePlus(ImagePlusReader.java:39)
	at xmipp.ij.commons.ImagePlusLoader.getImagePlus(ImagePlusLoader.java:108)
	at xmipp.viewer.models.MetadataGalleryTableModel.getImage(MetadataGalleryTableModel.java:119)
	at xmipp.viewer.models.MetadataGalleryTableModel.createImageItem(MetadataGalleryTableModel.java:225)
	at xmipp.viewer.models.MetadataGalleryTableModel.createItem(MetadataGalleryTableModel.java:197)
	at xmipp.viewer.models.ImageGalleryTableModel.getValueAt(ImageGalleryTableModel.java:179)
