### ISSUE TITLE
creating subset of SetOfXXXTiltPair is not working properly

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#541]
Version 1.0.1.
To reproduce:
1. run xmipp - extract particle pairs
2. create a subset from previous output
3. run any protocol, e.g. cl2d -> it will fail.

The problem is that in step 2 _particles_tilted.sqlite_ and _particles_untilted.sqlite_ output files are empty. However, _particles_pairs.sqlite_ and _subset.sqlite_ seems OK, so the resulting subset can be displayed in **Analyze results**.

**Comment by azazellochg** [comment]
If I add [here](https://github.com/I2PC/scipion/blob/devel-fixes/pyworkflow/em/protocol/protocol_batch.py#L401) 
```
outputU.write()
outputT.write()
```
then it works. I dont understand why append works (objects are added) but output sqlite is empty if these two lines are not present. Also, while looking into this, I discovered creating set of tilt pair mics is not working:
```
00012:   STARTED: createSetStep, step 1
00013:     2016-08-12 16:33:15.394132
00014:   Traceback (most recent call last):
00015:     File "/home/sharov/soft/scipion/pyworkflow/protocol/protocol.py", line 180, in run
00016:       self._run()
00017:     File "/home/sharov/soft/scipion/pyworkflow/protocol/protocol.py", line 226, in _run
00018:       resultFiles = self._runFunc()
00019:     File "/home/sharov/soft/scipion/pyworkflow/protocol/protocol.py", line 222, in _runFunc
00020:       return self._func(*self._args)
00021:     File "/home/sharov/soft/scipion/pyworkflow/em/protocol/protocol_batch.py", line 107, in createSetStep
00022:       output = self._createSubSetFromMicrographsTiltPair(inputObj)
00023:     File "/home/sharov/soft/scipion/pyworkflow/em/protocol/protocol_batch.py", line 370, in _createSubSetFromMicrographsTiltPair
00024:       outputU.append(untilted)
00025:     File "/home/sharov/soft/scipion/pyworkflow/em/data.py", line 766, in append
00026:       EMSet.append(self, image)
00027:     File "/home/sharov/soft/scipion/pyworkflow/object.py", line 1114, in append
00028:       self._insertItem(item)
00029:     File "/home/sharov/soft/scipion/pyworkflow/object.py", line 1118, in _insertItem
00030:       self._getMapper().insert(item)
00031:     File "/home/sharov/soft/scipion/pyworkflow/mapper/sqlite.py", line 587, in insert
00032:       *obj.getObjDict().values())
00033:     File "/home/sharov/soft/scipion/pyworkflow/mapper/sqlite.py", line 976, in insertObject
00034:       self.executeCommand(self.INSERT_OBJECT, args)
00035:   IntegrityError: PRIMARY KEY must be unique
00036:   Protocol failed: PRIMARY KEY must be unique
```

**Comment by azazellochg** [comment]
@delarosatrevin , could you check if 295bfda fix make sense to you?

**Comment by delarosatrevin** [comment]
@azazellochg It make a lot of sense. I did a small change in 3dd54b4ec309e9286e0f74198f0393d2b5815941, but I haven't test it.

**Comment by azazellochg** [comment]
@delarosatrevin thank you! I've checked both subsets and it works!

**Comment by delarosatrevin** [comment]
Great! Thanks to you for all your help!!
