### ISSUE TITLE
problem with relion refinement

### ISSUE THREAD

**Issue by sayanbhakta** [I2PC/scipion#547]
My refinement suddenly stopped at iteration no 11.
When I tried to re-run it, it shows following error. please help.

```

> Error during EXECUTE: maximum recursion depth exceeded while calling a Python object
> 
> Traceback:
> Traceback (most recent call last):
>   File "/data/scipion/pyworkflow/gui/form.py", line 1588, in _close
>     message = self.callback(self.protocol, onlySave)
>   File "/data/scipion/pyworkflow/gui/project/viewprotocols.py", line 1201, in _executeSaveProtocol
>     self.project.launchProtocol(prot)
>   File "/data/scipion/pyworkflow/project.py", line 340, in launchProtocol
>     'Cannot RE-LAUNCH protocol')
>   File "/data/scipion/pyworkflow/project.py", line 474, in _checkModificationAllowed
>     self._checkProtocolsDependencies(protocols, msg)
>   File "/data/scipion/pyworkflow/project.py", line 463, in _checkProtocolsDependencies
>     error = self._getProtocolsDependencies(protocols)
>   File "/data/scipion/pyworkflow/project.py", line 444, in _getProtocolsDependencies
>     node = self.getRunsGraph().getNode(prot.strId())
>   File "/data/scipion/pyworkflow/project.py", line 849, in getRunsGraph
>     runs = [r for r in self.getRuns(refresh=refresh) if not r.isChild()]
>   File "/data/scipion/pyworkflow/project.py", line 818, in getRuns
>     objectFilter=lambda o: isinstance(o, pwprot.Protocol))
>   File "/data/scipion/pyworkflow/mapper/sqlite.py", line 298, in selectAll
>     return self.__objectsFromRows(objRows, iterate, objectFilter)
>   File "/data/scipion/pyworkflow/mapper/sqlite.py", line 259, in __objectsFromRows
>     return [obj for obj in self.__iterObjectsFromRows(objRows, objectFilter)]
>   File "/data/scipion/pyworkflow/mapper/sqlite.py", line 245, in __iterObjectsFromRows
>     obj = self.__objFromRow(objRow)
>   File "/data/scipion/pyworkflow/mapper/sqlite.py", line 237, in __objFromRow
>     obj = self._buildObject(objClassName)
>   File "/data/scipion/pyworkflow/mapper/mapper.py", line 67, in _buildObject
>     return self.dictClasses[className](**kwargs)
>   File "/data/scipion/pyworkflow/em/protocol/protocol.py", line 54, in __init__
>     Protocol.__init__(self, **kwargs)
>   File "/data/scipion/pyworkflow/protocol/protocol.py", line 289, in __init__
>     self._definition = Form(self)
>   File "/data/scipion/pyworkflow/protocol/params.py", line 196, in __init__
>     self.addGeneralSection()
>   File "/data/scipion/pyworkflow/protocol/params.py", line 305, in addGeneralSection
>     help='Select run name label to identify this run.')
>   File "/data/scipion/pyworkflow/protocol/params.py", line 220, in addParam
>     return self.lastSection.addParam(*args, **kwargs)
>   File "/data/scipion/pyworkflow/protocol/params.py", line 129, in addParam
>     param = ParamClass(**kwargs)
>   File "/data/scipion/pyworkflow/protocol/params.py", line 345, in __init__
>     Param.__init__(self, paramClass=String, **args)
>   File "/data/scipion/pyworkflow/protocol/params.py", line 88, in __init__
>     FormElement.__init__(self, **args)
>   File "/data/scipion/pyworkflow/protocol/params.py", line 46, in __init__
>     OrderedObject.__init__(self, **args)
>   File "/data/scipion/pyworkflow/object.py", line 474, in __init__
>     Object.__init__(self, value, **kwargs)
>   File "/data/scipion/pyworkflow/object.py", line 47, in __init__
>     self._objIsPointer = kwargs.get('objIsPointer', False) # True if will be treated as a reference for storage
>   File "/data/scipion/pyworkflow/object.py", line 493, in __setattr__
>     issubclass(value.__class__, Object) and
> RuntimeError: maximum recursion depth exceeded while calling a Python object

```

**Comment by azazellochg** [comment]
Hi @sayanbhakta , this look serious. In the meantime, does it work if you create a copy of this protocol and try to run in Continue mode from iteration 10?

**Comment by sayanbhakta** [comment]
after making a copy, when I started from iteration 10, it's running....I wonder what actually happen!!...don't know whether it will collapse again or not...

**Comment by azazellochg** [comment]
@sayanbhakta could you provide a full log file of the failed run and also a workflow with all protocols linked to the failed one (click on one protocol box, click Ctrl+A, select Export) - json file? You could add txt extension to the files and attach them here.

**Comment by sayanbhakta** [comment]
attaching the required files
[run_log.txt](https://github.com/I2PC/scipion/files/390938/run_log.txt)
[workflow.txt](https://github.com/I2PC/scipion/files/390940/workflow.txt)

**Comment by delarosatrevin** [comment]
@sayanbhakta , thanks for let us know. I looked into the log and there is not hint about the unexpected stop. I think is not relating to Scipion but to the Relion process...still I have not idea why it stopped. 

The second error seems to be related to some inconsistency when re-running Relion protocols, I will check that later more carefully. Anyway, as @azazellochg pointed out, the way to proceed is to make a copy and use the 'continue from previous' run. In other protocols, it is the same as using the global 'Continue' mode and it will try to reuse the steps. In this particular case, there is only one big step for Relion, so if you re-run this step you will loose your previous iterations. Maybe we should add some warnings to make this point more clear. Any idea is welcome.

**Comment by delarosatrevin** [comment]
@azazellochg , maybe a way here could be to make the Relion protocols (and other that have the same iterative way and support continue from ) smarter and if they detect previous iterations, then will insert an step to continue  from previous one....without the need to make a copy. Maybe this way complicates a little bit the parameters are or are not allowed in the continue mode.
