### ISSUE TITLE
CTF protocol (xmipp) fails if tests defocus > 10 microns

### ISSUE THREAD

**Issue by rmarabini** [I2PC/scipion#592]
- compute defocus on a set on micrgraphs in range 0.5 8 microns
- recalculate some of them
- the protocol tries several defocus if the value is greater than 10 microns fail with error message

xmipp_ctf_estimate_from_psd --psd Runs/000585_XmippProtCTFMicrographs/extra/Ad41-crio2-20160606-_0029_1/xmipp_ctf.psd  --Q0 0.07 --downSamplingPerformed 2.0 --defocusU 114920.27 --defocusV 114447.69 --kV 200.0 --azimuthal_angle 72.04 --min_freq 0.05 --ctfmodelSize 256 --max_freq 0.13 --Cs 2.26 --sampling_rate 4.42 --defocus_range 5000
01862:   XMIPP_ERROR 2:  Incorrect argument received
01863:   Defocus cannot be larger than 10 microns (100,000 Angstroms)
01864:   File: software/em/xmipp/libraries/reconstruction/ctf_estimate_from_psd.cpp line: 338

**Comment by rmarabini** [comment]
If you try to continue by recalculating CTFs different from the ones that failed you get the message


01918:         Scipion: v1.0.1
01919:      currentDir: /home/gncondezo/ScipionUserData/projects/Ad41
01920:      workingDir: Runs/000585_XmippProtCTFMicrographs
01921:         runMode: Continue
01922:             MPI: 1
01923:         threads: 16
01924:   len(steps) 68 len(prevSteps) 59
01925:    Starting at step: 45
01926:    Running steps 
01927:   Traceback (most recent call last):
01928:     File "/usr/local/ScipionStable/scipion/pyworkflow/protocol/protocol.py", line 167, in run
01929:       self._run()
01930:     File "/usr/local/ScipionStable/scipion/pyworkflow/protocol/protocol.py", line 936, in _run
01931:       self._runSteps(startIndex)
01932:     File "/usr/local/ScipionStable/scipion/pyworkflow/protocol/protocol.py", line 820, in _runSteps
01933:       self._stepsExecutor.runSteps(self._steps, self._stepStarted, self._stepFinished)
01934:     File "/usr/local/ScipionStable/scipion/pyworkflow/protocol/executor.py", line 139, in runSteps
01935:       step = getRunnable()
01936:     File "/usr/local/ScipionStable/scipion/pyworkflow/protocol/executor.py", line 116, in getRunnable
01937:       all(steps[i-1].isFinished() for i in s._prerequisites)):
01938:     File "/usr/local/ScipionStable/scipion/pyworkflow/protocol/executor.py", line 116, in <genexpr>
01939:       all(steps[i-1].isFinished() for i in s._prerequisites)):
01940:   TypeError: unsupported operand type(s) for -: 'str' and 'int'
01941:   Cleaning temporarly files....
