### ISSUE TITLE
Analize Results of validate_overfitting does not work in devel

### ISSUE THREAD

**Issue by 1aviervargas** [I2PC/scipion#605]
josue@finlay:~> Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/local/scipion/software/lib/python2.7/lib-tk/Tkinter.py", line 1486, in __call__
    return self.func(*args)
  File "/usr/local/scipion/pyworkflow/gui/project/viewprotocols.py", line 1687, in _analyzeResultsClicked
    self._analyzeResults(prot)
  File "/usr/local/scipion/pyworkflow/gui/project/viewprotocols.py", line 1667, in _analyzeResults
    firstViewer.visualize(prot)
  File "/usr/local/scipion/pyworkflow/viewer.py", line 146, in visualize
    for view in self._visualize(obj, **kwargs):
  File "/usr/local/scipion/pyworkflow/em/packages/xmipp3/viewer_validate_overfitting.py", line 54, in _visualize
    fnOutput, xmipp.MDL_COUNT, xmipp.MDL_AVG)
  File "/usr/local/scipion/pyworkflow/em/packages/xmipp3/viewer_validate_overfitting.py", line 101, in _createPlot
    pylab.legend(loc='upper right' , fontsize = 11)
NameError: global name 'pylab' is not defined

**Comment by mohsenkazemi** [comment]
plotter fixed
