### ISSUE TITLE
Old movie-alignment protocol produces an error when selected (in devel)

### ISSUE THREAD

**Issue by delarosatrevin** [I2PC/scipion#637]
Seems related to the summary and the dim string:

Traceback (most recent call last):                                                                                                                                                           
  File "/usr/local/ScipionOther/scipion/software/lib/python2.7/lib-tk/Tkinter.py", line 1486, in __call__                                                                                    
    return self.func(*args)                                                                                                                                                                  
  File "/usr/local/ScipionOther/scipion/pyworkflow/gui/tree.py", line 250, in _onSelect                                                                                                      
    self.itemClick(obj)                                                                                                                                                                      
  File "/usr/local/ScipionOther/scipion/pyworkflow/gui/project/viewprotocols.py", line 1242, in _runTreeItemClick                                                                            
    self._updateSelection()                                                                                                                                                                  
  File "/usr/local/ScipionOther/scipion/pyworkflow/gui/project/viewprotocols.py", line 1229, in _updateSelection                                                                             
    self._fillSummary()                                                                                                                                                                      
  File "/usr/local/ScipionOther/scipion/pyworkflow/gui/project/viewprotocols.py", line 1469, in _fillSummary                                                                                 
    self.infoTree.setProvider(provider)                                                                                                                                                      
  File "/usr/local/ScipionOther/scipion/pyworkflow/gui/tree.py", line 235, in setProvider                                                                                                    
    self.update()                                                                                                                                                                            
  File "/usr/local/ScipionOther/scipion/pyworkflow/gui/tree.py", line 296, in update                                                                                                         
    objDict = self.provider.getObjectInfo(obj)
  File "/usr/local/ScipionOther/scipion/pyworkflow/gui/project/viewprotocols.py", line 503, in getObjectInfo
    'text': name, 'values': (str(labelObj),)}
  File "/usr/local/ScipionOther/scipion/pyworkflow/em/data.py", line 877, in __str__
    self._dimStr(), sampling)
  File "/usr/local/ScipionOther/scipion/pyworkflow/em/data.py", line 1783, in _dimStr
    x, y, z = self._firstDim

**Comment by delarosatrevin** [comment]
Fixed in 6a013a500c28809ff43583f9048a1f1c248970a3
