### ISSUE TITLE
cannot open shared libraries

### ISSUE THREAD

**Issue by brossa** [I2PC/scipion#748]
Hi everyone,
When trying to launch some tests I got some issues with shared libraries:
```
00001:   RUNNING PROTOCOL -----------------
00002:             PID: 32036
00003:         Scipion: devel (devel) devel
00004:      currentDir: /em/home/gu62vos/ScipionUserData/projects/TestRelionClassify2D
00005:      workingDir: Runs/000126_ProtRelionClassify2D
00006:         runMode: Continue
00007:             MPI: 4
00008:         threads: 1
00009:   len(steps) 3 len(prevSteps) 0
00010:    Starting at step: 1
00011:    Running steps 
00012:   STARTED: convertInputStep, step 1
00013:     2017-01-03 10:37:35.270146
00014:   Converting set from 'Runs/000070_ProtRelionPreprocessParticles/particles.sqlite' into 'Runs/000126_ProtRelionClassify2D/input_particles.star'
00015:   convertBinaryFiles: creating soft links.
00016:      Runs/000126_ProtRelionClassify2D/extra/particles.mrcs -> Runs/000070_ProtRelionPreprocessParticles/particles.mrcs
00017:   FINISHED: convertInputStep, step 1
00018:     2017-01-03 10:37:35.431371
00019:   STARTED: runRelionStep, step 2
00020:     2017-01-03 10:37:38.664148
00021:   mpirun -np 4 -bynode  `which relion_refine_mpi` --tau2_fudge 2 --scale  --iter 3 --norm  --memory_per_thread 2 --offset_range 5.0 --oversampling 1 --o Runs/000126_ProtRelionClassify2D/extra/relion --i Runs/000126_ProtRelionClassify2D/input_particles.star --particle_diameter 340 --K 4 --psi_step 10.0 --flatten_solvent  --zero_mask  --offset_step 2.0 --angpix 3.5  --j 1
00022:   --------------------------------------------------------------------------
00023:   The following command line options and corresponding MCA parameter have
00024:   been deprecated and replaced as follows:
00025:   
00026:     Command line options:
00027:       Deprecated:  --bynode, -bynode
00028:       Replacement: --map-by node
00029:   
00030:     Equivalent MCA parameter:
00031:       Deprecated:  rmaps_base_bynode
00032:       Replacement: rmaps_base_mapping_policy=node
00033:   
00034:   The deprecated forms *will* disappear in a future version of Open MPI.
00035:   Please update to the new syntax.
00036:   --------------------------------------------------------------------------
00037:   /em/software/scipion/scipion-devel/software/em/relion-1.4/bin/relion_refine_mpi: error while loading shared libraries: libibverbs.so.1: cannot open shared object file: No such file or directory
00038:   /em/software/scipion/scipion-devel/software/em/relion-1.4/bin/relion_refine_mpi: error while loading shared libraries: libibverbs.so.1: cannot open shared object file: No such file or directory
00039:   -------------------------------------------------------
00040:   Primary job  terminated normally, but 1 process returned
00041:   a non-zero exit code.. Per user-direction, the job has been aborted.
00042:   -------------------------------------------------------
00043:   --------------------------------------------------------------------------
00044:   mpirun detected that one or more processes exited with non-zero status, thus causing
00045:   the job to be terminated. The first process to do so was:
00046:   
00047:     Process name: [[53062,1],0]
00048:     Exit code:    127
00049:   --------------------------------------------------------------------------
00050:   Traceback (most recent call last):
00051:     File "/em/software/scipion/scipion-devel/pyworkflow/protocol/protocol.py", line 182, in run
00052:       self._run()
00053:     File "/em/software/scipion/scipion-devel/pyworkflow/protocol/protocol.py", line 228, in _run
00054:       resultFiles = self._runFunc()
00055:     File "/em/software/scipion/scipion-devel/pyworkflow/protocol/protocol.py", line 224, in _runFunc
00056:       return self._func(*self._args)
00057:     File "/em/software/scipion/scipion-devel/pyworkflow/em/packages/relion/protocol_base.py", line 602, in runRelionStep
00058:       self.runJob(self._getProgram(), params)
00059:     File "/em/software/scipion/scipion-devel/pyworkflow/protocol/protocol.py", line 1029, in runJob
00060:       self._stepsExecutor.runJob(self._log, program, arguments, **kwargs)
00061:     File "/em/software/scipion/scipion-devel/pyworkflow/protocol/executor.py", line 56, in runJob
00062:       env=env, cwd=cwd)
00063:     File "/em/software/scipion/scipion-devel/pyworkflow/utils/process.py", line 51, in runJob
00064:       return runCommand(command, env, cwd)
00065:     File "/em/software/scipion/scipion-devel/pyworkflow/utils/process.py", line 65, in runCommand
00066:       check_call(command, shell=True, stdout=sys.stdout, stderr=sys.stderr, env=env, cwd=cwd)
00067:     File "/em/software/scipion/scipion-devel/software/lib/python2.7/subprocess.py", line 540, in check_call
00068:       raise CalledProcessError(retcode, cmd)
00069:   CalledProcessError: Command 'mpirun -np 4 -bynode  `which relion_refine_mpi` --tau2_fudge 2 --scale  --iter 3 --norm  --memory_per_thread 2 --offset_range 5.0 --oversampling 1 --o Runs/000126_ProtRelionClassify2D/extra/relion --i Runs/000126_ProtRelionClassify2D/input_particles.star --particle_diameter 340 --K 4 --psi_step 10.0 --flatten_solvent  --zero_mask  --offset_step 2.0 --angpix 3.5  --j 1' returned non-zero exit status 127
00070:   Protocol failed: Command 'mpirun -np 4 -bynode  `which relion_refine_mpi` --tau2_fudge 2 --scale  --iter 3 --norm  --memory_per_thread 2 --offset_range 5.0 --oversampling 1 --o Runs/000126_ProtRelionClassify2D/extra/relion --i Runs/000126_ProtRelionClassify2D/input_particles.star --particle_diameter 340 --K 4 --psi_step 10.0 --flatten_solvent  --zero_mask  --offset_step 2.0 --angpix 3.5  --j 1' returned non-zero exit status 127
00071:   FAILED: runRelionStep, step 2
00072:     2017-01-03 10:37:39.486956
00073:   ------------------- PROTOCOL FAILED (DONE 2/3)
```
but libibverbs.so.1 exists in /usr/lib
and:

```
00001:   RUNNING PROTOCOL -----------------
00002:             PID: 29807
00003:         Scipion: devel (devel) devel
00004:      currentDir: /em/home/gu62vos/ScipionUserData/projects/TestXmippML2D
00005:      workingDir: Runs/000070_XmippProtML2D
00006:         runMode: Continue
00007:             MPI: 2
00008:         threads: 2
00009:   len(steps) 3 len(prevSteps) 0
00010:    Starting at step: 1
00011:    Running steps 
00012:   STARTED: convertInputStep, step 1
00013:     2017-01-03 09:46:13.475538
00014:   FINISHED: convertInputStep, step 1
00015:     2017-01-03 09:46:13.637069
00016:   STARTED: runJob, step 2
00017:     2017-01-03 09:46:16.904574
00018:   mpirun -np 2 -bynode  `which xmipp_mpi_ml_align2d`  -i Runs/000070_XmippProtML2D/tmp/input_particles.xmd --oroot Runs/000070_XmippProtML2D/ml2d_ --nref 2 --fast --thr 2 --iter 3 --mirror
00019:   --------------------------------------------------------------------------
00020:   The following command line options and corresponding MCA parameter have
00021:   been deprecated and replaced as follows:
00022:   
00023:     Command line options:
00024:       Deprecated:  --bynode, -bynode
00025:       Replacement: --map-by node
00026:   
00027:     Equivalent MCA parameter:
00028:       Deprecated:  rmaps_base_bynode
00029:       Replacement: rmaps_base_mapping_policy=node
00030:   
00031:   The deprecated forms *will* disappear in a future version of Open MPI.
00032:   Please update to the new syntax.
00033:   --------------------------------------------------------------------------
00034:   /em/software/scipion/scipion-devel/software/em/xmipp/bin/xmipp_mpi_ml_align2d: error while loading shared libraries: libXmippAlglib.so: cannot open shared object file: No such file or directory
00035:   /em/software/scipion/scipion-devel/software/em/xmipp/bin/xmipp_mpi_ml_align2d: error while loading shared libraries: libXmippAlglib.so: cannot open shared object file: No such file or directory
00036:   -------------------------------------------------------
00037:   Primary job  terminated normally, but 1 process returned
00038:   a non-zero exit code.. Per user-direction, the job has been aborted.
00039:   -------------------------------------------------------
00040:   --------------------------------------------------------------------------
00041:   mpirun detected that one or more processes exited with non-zero status, thus causing
00042:   the job to be terminated. The first process to do so was:
00043:   
00044:     Process name: [[50827,1],0]
00045:     Exit code:    127
00046:   --------------------------------------------------------------------------
00047:   Traceback (most recent call last):
00048:     File "/em/software/scipion/scipion-devel/pyworkflow/protocol/protocol.py", line 182, in run
00049:       self._run()
00050:     File "/em/software/scipion/scipion-devel/pyworkflow/protocol/protocol.py", line 228, in _run
00051:       resultFiles = self._runFunc()
00052:     File "/em/software/scipion/scipion-devel/pyworkflow/protocol/protocol.py", line 224, in _runFunc
00053:       return self._func(*self._args)
00054:     File "/em/software/scipion/scipion-devel/pyworkflow/protocol/protocol.py", line 1029, in runJob
00055:       self._stepsExecutor.runJob(self._log, program, arguments, **kwargs)
00056:     File "/em/software/scipion/scipion-devel/pyworkflow/protocol/executor.py", line 56, in runJob
00057:       env=env, cwd=cwd)
00058:     File "/em/software/scipion/scipion-devel/pyworkflow/utils/process.py", line 51, in runJob
00059:       return runCommand(command, env, cwd)
00060:     File "/em/software/scipion/scipion-devel/pyworkflow/utils/process.py", line 65, in runCommand
00061:       check_call(command, shell=True, stdout=sys.stdout, stderr=sys.stderr, env=env, cwd=cwd)
00062:     File "/em/software/scipion/scipion-devel/software/lib/python2.7/subprocess.py", line 540, in check_call
00063:       raise CalledProcessError(retcode, cmd)
00064:   CalledProcessError: Command 'mpirun -np 2 -bynode  `which xmipp_mpi_ml_align2d`  -i Runs/000070_XmippProtML2D/tmp/input_particles.xmd --oroot Runs/000070_XmippProtML2D/ml2d_ --nref 2 --fast --thr 2 --iter 3 --mirror' returned non-zero exit status 127
00065:   Protocol failed: Command 'mpirun -np 2 -bynode  `which xmipp_mpi_ml_align2d`  -i Runs/000070_XmippProtML2D/tmp/input_particles.xmd --oroot Runs/000070_XmippProtML2D/ml2d_ --nref 2 --fast --thr 2 --iter 3 --mirror' returned non-zero exit status 127
00066:   FAILED: runJob, step 2
00067:     2017-01-03 09:46:17.595380
00068:   ------------------- PROTOCOL FAILED (DONE 2/3)
```
but libXmippAlglib.so exists in $SCIPION_DIR/software/lib.

When I added the Path to $LD_LIBRARY_PATH, nothing changed. Do I need to fix some config files? I am using Debian 8.6, the devel Version of Scipion and OpenMPI 1.10.5 built with --disable-dlopen and --enable-orterun-prefix-by-default.

Thanks in advance!

**Comment by brossa** [comment]
okay. I managed to solve it. There was a problem with the script I used to launch scipion.
Sorry..
