### ISSUE TITLE
One of the basic tests failed

### ISSUE THREAD

**Issue by delarosatrevin** [I2PC/scipion#825]
In my newly installed scipion in OpenSuse Tumbleweed, the following test fails
scipion tests em.data.test_convert_xmipp

It seems to be related to some gold file in the emx dataset. 

[   FAILED ] TestReconstruct.test_reconstRotandShiftFlip

Traceback (most recent call last):
  File "/home/josem/installs/scipion/software/lib/python2.7/unittest/case.py", line 329, in run       
    testMethod()                                                                                      
  File "/home/josem/installs/scipion/pyworkflow/tests/em/data/test_convert_xmipp.py", line 789, in test_reconstRotandShiftFlip                                                                              
    self.launchTest('reconstRotandShiftFlip', mList, alignType=ALIGN_PROJ)
  File "/home/josem/installs/scipion/pyworkflow/tests/em/data/test_convert_xmipp.py", line 210, in launchTest
    "Different data files:\n>%s\n<%s" % (goldFn, outputFn))
  File "/home/josem/installs/scipion/software/lib/python2.7/unittest/case.py", line 422, in assertTrue
    raise self.failureException(msg)
AssertionError: Different data files:
>/home/josem/installs/scipion/data/tests/emx/reconstRotandShiftFlip_Gold_output.vol
</home/josem/ScipionUserData/Tests/TestReconstruct/reconstRotandShiftFlip_output.vol

**Comment by pconesa** [comment]
It works fine here!. Does it still fail in your machine?

**Comment by pconesa** [comment]
@delarosatrevin , does this still happens?

**Comment by delarosatrevin** [comment]
I will test it again.

**Comment by delarosatrevin** [comment]
Still failing with the same test, given the same error.
[   FAILED ] TestReconstruct.test_reconstRotandShiftFlip

Traceback (most recent call last):
  File "/home/josem/installs/scipion/software/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/home/josem/installs/scipion/pyworkflow/tests/em/data/test_convert_xmipp.py", line 789, in test_reconstRotandShiftFlip
    self.launchTest('reconstRotandShiftFlip', mList, alignType=ALIGN_PROJ)
  File "/home/josem/installs/scipion/pyworkflow/tests/em/data/test_convert_xmipp.py", line 210, in launchTest
    "Different data files:\n>%s\n<%s" % (goldFn, outputFn))
  File "/home/josem/installs/scipion/software/lib/python2.7/unittest/case.py", line 422, in assertTrue
    raise self.failureException(msg)
AssertionError: Different data files:
>/home/josem/installs/scipion/data/tests/emx/reconstRotandShiftFlip_Gold_output.vol
</home/josem/ScipionUserData/Tests/TestReconstruct/reconstRotandShiftFlip_output.vol
>>>> python /home/josem/installs/scipion/scipion testdata --download xmipp_tutorial

Scipion  release-1.1 (2017-03-03) 0144300f99

I just updated the release-1.1 branch before running the test.

**Comment by pconesa** [comment]
Fails in @1aviervargas machine (Also tumbleweed) but not in mine(ubuntu) or debian (nolan)...Could this be due to the OS distribution?

**Comment by azazellochg** [comment]
@delarosatrevin could you rerun scipion tests xmipp3.tests.test_convert_xmipp ? Works for me

**Comment by delarosatrevin** [comment]
This is quite an old issue, I will close it until further notice.
