### ISSUE TITLE
NVCC_LIB is added to env when there is no CUDA set

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#882]
commit 775abc9 breaks devel for me. I have CUDA = False in config.
I can't start scipion, since it tries to find NVCC_LIB var which does not exist

```
Traceback (most recent call last):
  File "/home/azazello/soft/scipion/pyworkflow/utils/reflection.py", line 49, in getModules
    m = __import__(f)
  File "/home/azazello/soft/scipion/pyworkflow/em/packages/gautomatch/__init__.py", line 35, in <module>
    from viewer import GautomatchViewer
  File "/home/azazello/soft/scipion/pyworkflow/em/packages/gautomatch/viewer.py", line 33, in <module>
    from pyworkflow.em.packages.xmipp3.convert import *
  File "/home/azazello/soft/scipion/pyworkflow/em/packages/xmipp3/__init__.py", line 122, in <module>
    _environ = getEnviron()
  File "/home/azazello/soft/scipion/pyworkflow/em/packages/xmipp3/xmipp3.py", line 64, in getEnviron
    'LD_LIBRARY_PATH': os.environ['NVCC_LIBDIR']
  File "/home/azazello/soft/scipion/software/lib/python2.7/UserDict.py", line 23, in __getitem__
    raise KeyError(key)
KeyError: 'NVCC_LIBDIR'
```

**Comment by pconesa** [comment]
Thanks Gregory...

What happen if you add that variable, but empty (as it would be by 
default?). Will it work?

In anycase we need to consider this case..people having old config files 
but running recent code, which I think is your case, and many others here.

Does it sound right?

Cheers, Pablo.

**Comment by azazellochg** [comment]
Hi Pablo,
indeed it works. I was not aware that config file was updated. Thanks!

**Comment by pconesa** [comment]
Thanks for the feedback....we are updating the config file and 
sometimes, although we try not to break executions, sometimes we fail.

But usually an update of the config fixes it.

You are very welcome!

**Comment by azazellochg** [comment]
@pconesa just a small fix needed:
I just launched Scipion release-1.1\n' (2017-03-16) 712c4fd0b1 on my laptop without cuda. It gives a warning: `None of the variables: ('MOTIONCORR_CUDA_LIB', 'CUDA_LIB') found in the Environment. Please check scipion.conf files.`
If I add one of this vars and set it to None then it complains tha path blabla/None does not exist...

**Comment by pconesa** [comment]
Hi Gregory! I found the same problem and should be fixed now on 
release-1.1. Let me know if it is not.

Thanks for reporting. ;-)
