### ISSUE TITLE
TestCtfStream unlimited

### ISSUE THREAD

**Issue by pconesa** [I2PC/scipion#884]
./scipion test tests.em.protocols.test_protocols_ctf_monitor.TestCtfStream seems to take unlimited time.

**Comment by rmarabini** [comment]
@pconesa, this tests seems to work in my computer. It creates 3 micrographs   of 4096 4096 waiting 5 seconds between creation. Protocol total time is about 30 seconds.

**Comment by pconesa** [comment]
@rmarabini , I'm closing this. Today test has pass in buildbot...sorry and thanks.

**Comment by pconesa** [comment]
It has failed today in buildbot...may be needs more time to wait for the output?
 Running steps 
ESC[35mSTARTEDESC[0m: monitorStep, step 1
  2017-03-09 01:30:37.343979
Traceback (most recent call last):
  File "/home/buildbot-slave/data/slave/release11_Protocol_Tests/build/pyworkflow/protocol/protocol.py", line 184, in run
    self._run()
  File "/home/buildbot-slave/data/slave/release11_Protocol_Tests/build/pyworkflow/protocol/protocol.py", line 230, in _run
    resultFiles = self._runFunc()
  File "/home/buildbot-slave/data/slave/release11_Protocol_Tests/build/pyworkflow/protocol/protocol.py", line 226, in _runFunc
    return self._func(*self._args)
  File "/home/buildbot-slave/data/slave/release11_Protocol_Tests/build/pyworkflow/em/protocol/monitors/protocol_monitor_ctf.py", line 83, in monitorStep
    self.createMonitor().loop()
  File "/home/buildbot-slave/data/slave/release11_Protocol_Tests/build/pyworkflow/em/protocol/monitors/protocol_monitor.py", line 162, in loop
    finished = self.step()
  File "/home/buildbot-slave/data/slave/release11_Protocol_Tests/build/pyworkflow/em/protocol/monitors/protocol_monitor_ctf.py", line 151, in step
    CTFset = prot.outputCTF.getIdSet()
AttributeError: 'ProtCTFFind' object has no attribute 'outputCTF'
ESC[31mProtocol failed: 'ProtCTFFind' object has no attribute 'outputCTF'ESC[0m
ESC[35mFAILEDESC[0m: monitorStep, step 1

**Comment by rmarabini** [comment]
Uhm, the protocol "creates" a collection of micrographs which CTF is
computed by ctffind. It may be the case that ctffind fails in computing
some of the CTFs. Is the project available in Bblbot?

    Roberto

**Comment by pconesa** [comment]
Now buildbot is stuck (58 minutes) running TestCtfStream.  It's weird, I've run it manually on nolan (were buildbot runs it) and it works, but inside "buildbot" context seems to be different. I'm on skype, google chat is you want to discuss it or get to the project.

**Comment by pconesa** [comment]
Got some more details.....: Ctf is failing and therefore is waiting for something that will never happen:

Error in the log is:

ProtCTFFind' object has no attribute 'getAcquisition


I can see 3 things to improve here:
1.- To fix it..
2.- If CTFFind fails....test should fail.
3.- This test could have a just in case "timeout", so it does wait forever, still running: 2 hours. I can see it has but is too high 2:47 minutes, which matches the duration of the test in buildbot.

**Comment by rmarabini** [comment]
Hi,

I need to see the execution in Bblbot so I understand why ctffind fails.
(May be on Monday?)

     Roberto

**Comment by pconesa** [comment]
Sure! on monday is fine.
