### ISSUE TITLE
movie extract particles fails

### ISSUE THREAD

**Issue by azazellochg** [I2PC/scipion#895]
Reported by Simone Pellegrino in v1.0.1
I confirm this bug is still present in devel.
```
00003:         Scipion:  devel (2017-03-08) f54d260
00004:      currentDir: /lmb/home/gsharov/ScipionUserData/projects/TestImportMovies
00005:      workingDir: Runs/000423_XmippProtExtractMovieParticles
00006:         runMode: Continue
00007:             MPI: 1
00008:         threads: 1
00009:   len(steps) 2 len(prevSteps) 0
00010:    Starting at step: 1
00011:    Running steps 
00012:   STARTED: processMovieStep, step 1
00013:     2017-03-09 19:28:51.491591
00014:   Traceback (most recent call last):
00015:     File "/lmb/home/gsharov/soft/scipion/pyworkflow/protocol/protocol.py", line 184, in run
00016:       self._run()
00017:     File "/lmb/home/gsharov/soft/scipion/pyworkflow/protocol/protocol.py", line 230, in _run
00018:       resultFiles = self._runFunc()
00019:     File "/lmb/home/gsharov/soft/scipion/pyworkflow/protocol/protocol.py", line 226, in _runFunc
00020:       return self._func(*self._args)
00021:   TypeError: processMovieStep() takes exactly 3 arguments (4 given)
00022:   Protocol failed: processMovieStep() takes exactly 3 arguments (4 given)
00023:   FAILED: processMovieStep, step 1
00024:     2017-03-09 19:28:51.500009
00025:   ------------------- PROTOCOL FAILED (DONE 1/2)
```

PS. Actually I didn't find a test for this protocol...

**Comment by pconesa** [comment]
wow! I'm surprised....we are importing movies almost everyday..

Is this running the TestImportMovies test?

**Comment by pconesa** [comment]
Sorry, @azazellochg , I can see now that we are talking about extract particles. We'll check this.

**Comment by pconesa** [comment]
It seems that the 'processMovieStep' signature has changed
