### ISSUE TITLE
join sets protocol fails joining several volumes

### ISSUE THREAD

**Issue by josuegbl** [I2PC/scipion#966]
the error is the following: 
00001:   RUNNING PROTOCOL -----------------
00002:             PID: 22362
00003:         Scipion:  release-1.1 (2017-04-20) 1f58b5a
00004:      currentDir: /home/josue/ScipionUserData/projects/*******
00005:      workingDir: Runs/002205_ProtUnionSet
00006:         runMode: Continue
00007:             MPI: 1
00008:         threads: 1
00009:   len(steps) 1 len(prevSteps) 0 
00010:    Starting at step: 1
00011:    Running steps 
00012:   STARTED: createOutputStep, step 1
00013:     2017-04-25 10:34:12.526372
00014:   Traceback (most recent call last):
00015:     File "/usr/local/scipion/pyworkflow/protocol/protocol.py", line 182, in run
00016:       self._run()
00017:     File "/usr/local/scipion/pyworkflow/protocol/protocol.py", line 228, in _run
00018:       resultFiles = self._runFunc()
00019:     File "/usr/local/scipion/pyworkflow/protocol/protocol.py", line 224, in _runFunc
00020:       return self._func(*self._args)
00021:     File "/usr/local/scipion/pyworkflow/em/protocol/protocol_sets.py", line 135, in createOutputStep
00022:       outputSet = getattr(self, "_create%s" % set1.getClassName())()
00023:   AttributeError: 'ProtUnionSet' object has no attribute '_createVolume'
00024:   Protocol failed: 'ProtUnionSet' object has no attribute '_createVolume'
00025:   FAILED: createOutputStep, step 1
00026:     2017-04-25 10:34:12.528745
00027:   ------------------- PROTOCOL FAILED (DONE 1/1)

**Comment by delarosatrevin** [comment]
This protocol is designed to join sets...not individual elements.

**Comment by josuegbl** [comment]
OK, but what do you do if you want join several individual volumes into a only single set? I think that if the protocol not support this option, or fix, it or remove the option to select individual elements to join.

**Comment by pconesa** [comment]
Let's fix this by:
A: Offer only single volumes
B: Fix it and accept set of volumes

Whatever is safer!

**Comment by pconesa** [comment]
We went for option A, right? @josuegbl

**Comment by josuegbl** [comment]
NO @pconesa, just the opposite, only accept setOfVolumes.

2017-06-02 18:35 GMT+02:00 Pablo Conesa <notifications@github.com>:

**Comment by pconesa** [comment]
This is not fixed in devel! hmmmm @josegutab ?
